name: mup-parallel
root: ./
pre_window: bash
on_project_exit: >-
  tmux kill-session -t mup-parallel
windows:
  - deploy:
      layout: tiled
      panes:
        - instructions:
            - tmux set pane-border-status bottom
            - tmux select-pane -t 0 -T Instructions
            - node ./utils/tmux-instructions.js

        <% apps.forEach(({ app, environment, configFolder, command, prettyCommand, runSetup }, i) => { %>
        - <%- app %>-<%- environment %>:
            - tmux set pane-border-status bottom
            - export NPM_CONFIG_PREFIX=""
            <% if (runSetup) { %>
            - (cd ../scripts && bash setup-microservice.sh <%- app %>)
            <% } %>
            - tmux select-pane -t <%- i + 1 %> -T "<%- prettyCommand %> - <%- app %>"
            - cd <%- configFolder %>
            - METEOR_ALLOW_SUPERUSER=true EPOTEK_RUN_PARALLEL=true <%- command %> || echo "FAILED"
            - echo "DONE"

           <% }) %>
