export const NOTARY_FEES = 0.05;
export const AMORTIZATION_STOP = 0.65;
export const MAINTENANCE_REAL = 0.005;
export const MAINTENANCE_FINMA = 0.01;
export const INTERESTS_FINMA = 0.05;
export const MAX_BORROW_RATIO_PRIMARY_PROPERTY = 0.8;
export const MAX_BORROW_RATIO_OTHER = 0.7;
export const MAX_BORROW_RATIO_WITH_INSURANCE = 0.9;

export const FORTUNE_WARNING_TIGHT = 'FORTUNE_WARNING_TIGHT';
export const INCOME_WARNING_TIGHT = 'INCOME_WARNING_TIGHT';
export const FORTUNE_ERROR = 'FORTUNE_ERROR';
export const INCOME_ERROR = 'INCOME_ERROR';
