export const NOTARY_FEES = 0.05; // Percent
export const AMORTIZATION_STOP = 0.65; // Percent
export const MAINTENANCE_REAL = 0.005; // Percent
export const MAINTENANCE_FINMA = 0.01; // Percent
export const INTERESTS_FINMA = 0.05; // Percent
export const APPROXIMATE_LPP_FEES = 0.1; // Percent
export const DEFAULT_AMORTIZATION = 0.01; // Percent of property value
export const MAX_AMORTIZATION_DURATION = 15; // Years
export const DEFAULT_INTEREST_RATE = 0.015; // Percent, Use 1.5% by default
export const MAX_BORROW_RATIO_PRIMARY_PROPERTY = 0.8; // Percent
export const MAX_BORROW_RATIO_OTHER = 0.7; // Percent
export const MAX_BORROW_RATIO_WITH_INSURANCE = 0.9; // Percent
export const MAX_INCOME_RATIO = 1 / 3; // Percent
export const MAX_INCOME_RATIO_TIGHT = 0.38; // Percent
export const FORTUNE_WARNING_TIGHT = 'FORTUNE_WARNING_TIGHT';
export const INCOME_WARNING_TIGHT = 'INCOME_WARNING_TIGHT';
export const FORTUNE_ERROR = 'FORTUNE_ERROR';
export const INCOME_ERROR = 'INCOME_ERROR';
export const CURRENCY = 'CHF';
export const MIN_CASH = 0.1; // Percent of property value
