import { ACQUISITION_CHANNELS } from '../users/userConstants';

export const DRIP_TAGS = {
  TEST: 'TEST',
  PROMO: 'PROMO',
  ORGANIC: 'ORGANIC',
  CALENDLY: 'CALENDLY',
  LOST: 'LOST',
  QUALIFIED: 'QUALIFIED',
  [ACQUISITION_CHANNELS.REFERRAL_API]: ACQUISITION_CHANNELS.REFERRAL_API,
  [ACQUISITION_CHANNELS.REFERRAL_ORGANIC]:
    ACQUISITION_CHANNELS.REFERRAL_ORGANIC,
  [ACQUISITION_CHANNELS.REFERRAL_PRO]: ACQUISITION_CHANNELS.REFERRAL_PRO,
  [ACQUISITION_CHANNELS.REFERRAL_ADMIN]: ACQUISITION_CHANNELS.REFERRAL_ADMIN,
};

export const DRIP_ACTIONS = {
  USER_CREATED: 'User created',
  USER_VALIDATED: 'User validated',
  USER_QUALIFIED: 'User qualified',
  TEST_ACTION: 'Test action',
  LOAN_REMOVED_FROM_PROMOTION: 'Removed from promotion',
};
