import { PROMOTION_OPTION_SOLVENCY } from "../promotionOptions/promotionOptionConstants";

export const PROMOTION_RESERVATIONS_COLLECTION = 'promotionReservations';

export const PROMOTION_RESERVATIONS_QUERIES = {
  PROMOTION_RESERVATIONS: 'PROMOTION_RESERVATIONS',
};

export const AGREEMENT_STATUSES = {
  UNSIGNED: 'UNSIGNED',
  SIGNED: 'SIGNED',
  WAITING: 'WAITING',
};

export const DEPOSIT_STATUSES = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
};

export const PROMOTION_RESERVATION_LENDER_STATUS = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  VALIDATED: 'VALIDATED',
  REJECTED: 'REJECTED',
};

export const PROMOTION_RESERVATION_STATUS = {
  ACTIVE: 'ACTIVE',
  WAITLIST: 'WAITLIST',
  CANCELED: 'CANCELED',
  COMPLETED: 'COMPLETED',
};

export const PROMOTION_RESERVATION_MORTGAGE_CERTIFICATION_STATUS = {
  ...PROMOTION_OPTION_SOLVENCY,
  CALCULATED: 'CALCULATED',
};

export const PROMOTION_RESERVATION_DOCUMENTS = {
  RESERVATION_AGREEMENT: 'RESERVATION_AGREEMENT',
  DEPOSIT_JUSTIFICATION: 'DEPOSIT_JUSTIFICATION',
  NOMINATIVE_PURCHASE_ACT: 'NOMINATIVE_PURCHASE_ACT',
  NOMINATIVE_SHARE_GC_CONTRACT: 'NOMINATIVE_SHARE_GC_CONTRACT',
};
