import { PROMOTION_OPTION_SOLVENCY } from '../promotionOptions/promotionOptionConstants';

export const PROMOTION_RESERVATIONS_COLLECTION = 'promotionReservations';

export const PROMOTION_RESERVATIONS_QUERIES = {
  PROMOTION_RESERVATIONS: 'PROMOTION_RESERVATIONS',
};

export const PROMOTION_RESERVATION_STATUS = {
  CANCELED: 'CANCELED',
  EXPIRED: 'EXPIRED',
  WAITLIST: 'WAITLIST',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
};

export const AGREEMENT_STATUSES = {
  UNSIGNED: 'UNSIGNED',
  WAITING: 'WAITING',
  SIGNED: 'SIGNED',
};

export const DEPOSIT_STATUSES = {
  UNPAID: 'UNPAID',
  PAID: 'PAID',
};

export const PROMOTION_RESERVATION_BANK_STATUS = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  REJECTED: 'REJECTED',
  VALIDATED: 'VALIDATED',
  VALIDATED_WITH_CONDITIONS: 'VALIDATED_WITH_CONDITIONS',
};

export const PROMOTION_RESERVATION_MORTGAGE_CERTIFICATION_STATUS = {
  TO_BE_VERIFIED: 'TO_BE_VERIFIED',
  ...PROMOTION_OPTION_SOLVENCY,
};

export const PROMOTION_RESERVATION_DOCUMENTS = {
  RESERVATION_AGREEMENT: 'RESERVATION_AGREEMENT',
  DEPOSIT_JUSTIFICATION: 'DEPOSIT_JUSTIFICATION',
  NOMINATIVE_PURCHASE_ACT: 'NOMINATIVE_PURCHASE_ACT',
  NOMINATIVE_SHARE_GC_CONTRACT: 'NOMINATIVE_SHARE_GC_CONTRACT',
};
