export const PROMOTION_RESERVATIONS_COLLECTION = 'promotionReservations';

export const PROMOTION_RESERVATIONS_QUERIES = {
  // Insert your queries name here
  // Example:
  // EXAMPLE_QUERIE: 'EXAMPLE_QUERIE',
};

export const PROMOTION_RESERVATION_LENDER_STATUS = {
  NONE: 'NONE',
  WAITING: 'WAITING',
  VALIDATED: 'VALIDATED',
  REJECTED: 'REJECTED',
};

export const PROMOTION_RESERVATION_STATUS = {
  ACTIVE: 'ACTIVE',
  WAITLIST: 'WAITLIST',
  CANCELED: 'CANCELED',
  COMPLETED: 'COMPLETED',
};

export const PROMOTION_RESERVATION_MORTGAGE_CERTIFICATION_STATUS = {
  NONE: 'NONE',
  CALCULATED: 'CALCULATED',
  VALIDATED: 'VALIDATED',
};

export const PROMOTION_RESERVATION_DOCUMENTS = {
  RESERVATION_AGREEMENT: 'RESERVATION_AGREEMENT',
  DEPOSIT_JUSTIFICATION: 'DEPOSIT_JUSTIFICATION',
  NOMINATIVE_PURCHASE_ACT: 'NOMINATIVE_PURCHASE_ACT',
  NOMINATIVE_SHARE_GC_CONTRACT: 'NOMINATIVE_SHARE_GC_CONTRACT',
};
