export const INSURANCE_PRODUCTS_COLLECTION = 'insuranceProducts';

export const INSURANCE_PRODUCT_CATEGORIES = {
  '3A_INSURANCE': '3A_INSURANCE',
  '3A_BANK': '3A_BANK',
  '3B': '3B',
};

export const INSURANCE_PRODUCT_FEATURES = {
  GUARANTEED_CAPITAL: 'GUARANTEED_CAPITAL',
  NON_GUARANTEED_CAPITAL: 'NON_GUARANTEED_CAPITAL',
  DEATH_CAPITAL: 'DEATH_CAPITAL',
  DISABILITY_PENSION: 'DISABILITY_PENSION',
};
