import '../activities/links';
import '../borrowers/links';
import '../contacts/links';
import '../lenderRules/links';
import '../lenders/links';
import '../loans/links';
import '../lots/links';
import '../mortgageNotes/links';
import '../notifications/links';
import '../offers/links';
import '../organisations/links';
import '../promotionLots/links';
import '../promotionOptions/links';
import '../promotions/links';
import '../properties/links';
import '../revenues/links';
import '../tasks/links';
import '../users/links';
import '../sessions/links';
import '../insuranceRequests/links';
import '../insurances/links';
import LinkInitializer from './LinkInitializer';

LinkInitializer.setLinks();
