phraseapp:
  access_token: 50ddde6f0a3907b62bd6afb908c32804892a57dcfdbafc13a28163cf46136dc1
  project_id: 63a28b9dfe3d6e6ecb24cfc5c7f9c206
  push:
    sources:
    - file: build/lang/<locale_name>.json
      params:
        file_format: react_simple_json
  pull:
    targets:
    - file: build/lang/<locale_name>.json
      params:
        file_format: react_simple_json
