// Not actually used to create a meteor collection, but useful to switch()
// on collection names
export { ROLES } from './roles/roleConstants';

export const USERS_COLLECTION = 'users';

export const USER_QUERIES = {
  ADMIN_USERS: 'ADMIN_USERS',
  APP_USER: 'APP_USER',
  INCOHERENT_ASSIGNEES: 'INCOHERENT_ASSIGNEES',
  PRO_REFERRED_BY: 'PRO_REFERRED_BY',
  PRO_USER: 'PRO_USER',
  USER_EMAILS: 'USER_EMAILS',
  USER_SEARCH: 'USER_SEARCH',
};

export const USER_EVENTS = {
  USER_CREATED: 'USER_CREATED',
};

export const LOCAL_STORAGE_REFERRAL = 'REFERRAL_ID';
export const LOCAL_STORAGE_OLD_REFERRAL = 'OLD_REFERRAL_ID';

export const ACQUISITION_CHANNELS = {
  REFERRAL_PRO: 'REFERRAL_PRO',
  REFERRAL_ADMIN: 'REFERRAL_ADMIN',
  REFERRAL_API: 'REFERRAL_API',
  REFERRAL_ORGANIC: 'REFERRAL_ORGANIC',
  GOOGLE: 'GOOGLE',
  NEWSLETTER: 'NEWSLETTER',
  FRIENDS: 'FRIENDS',
  ADVERTISING: 'ADVERTISING',
  PAPER_ARTICLE: 'PAPER_ARTICLE',
  "tout l'immobilier": "tout l'immobilier",
  WEBSITE: 'WEBSITE',
  FACEBOOK: 'FACEBOOK',
  LINKEDIN: 'LINKEDIN',
};

export const OFFICES = {
  GENEVA: 'GENEVA',
  LAUSANNE: 'LAUSANNE',
};

export const ASSIGNEE = {
  NONE: 'NONE',
  ROUND_ROBIN: 'ROUND_ROBIN',
};

export const USER_STATUS = {
  PROSPECT: 'PROSPECT',
  QUALIFIED: 'QUALIFIED',
  LOST: 'LOST',
};
