// flow-typed signature: 98122a996796bf5ba6894a683e66b372
// flow-typed version: <<STUB>>/babel-plugin-react-intl_vhttps://github.com/Floriferous/babel-plugin-react-intl/tarball/master/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-intl/scripts/build-fixtures' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/src/print-icu-message' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/defineMessages/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/defineMessages/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/descriptionsAsObjects/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/descriptionsAsObjects/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/enforceDescriptions/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/extractSourceLocation/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/extractSourceLocation/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/FormattedHTMLMessage/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/FormattedHTMLMessage/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/FormattedMessage/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/FormattedMessage/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/icuSyntax/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/moduleSourceName/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/moduleSourceName/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/fixtures/removeDescriptions/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-react-intl/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-react-intl/scripts/build-fixtures.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/scripts/build-fixtures'>;
}
declare module 'babel-plugin-react-intl/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/src/index'>;
}
declare module 'babel-plugin-react-intl/src/print-icu-message.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/src/print-icu-message'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/defineMessages/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/defineMessages/actual'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/defineMessages/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/defineMessages/expected'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/descriptionsAsObjects/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/descriptionsAsObjects/actual'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/descriptionsAsObjects/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/descriptionsAsObjects/expected'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/enforceDescriptions/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/enforceDescriptions/actual'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/extractSourceLocation/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/extractSourceLocation/actual'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/extractSourceLocation/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/extractSourceLocation/expected'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/FormattedHTMLMessage/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/FormattedHTMLMessage/actual'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/FormattedHTMLMessage/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/FormattedHTMLMessage/expected'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/FormattedMessage/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/FormattedMessage/actual'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/FormattedMessage/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/FormattedMessage/expected'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/icuSyntax/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/icuSyntax/actual'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/moduleSourceName/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/moduleSourceName/actual'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/moduleSourceName/expected.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/moduleSourceName/expected'>;
}
declare module 'babel-plugin-react-intl/test/fixtures/removeDescriptions/actual.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/fixtures/removeDescriptions/actual'>;
}
declare module 'babel-plugin-react-intl/test/index.js' {
  declare module.exports: $Exports<'babel-plugin-react-intl/test/index'>;
}
