// flow-typed signature: 26934b6dba0fd5204b1229297a060bbd
// flow-typed version: <<STUB>>/babel-preset-meteor_v7.0.0-beta.47/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-meteor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-meteor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-meteor/modern' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-meteor/index' {
  declare module.exports: $Exports<'babel-preset-meteor'>;
}
declare module 'babel-preset-meteor/index.js' {
  declare module.exports: $Exports<'babel-preset-meteor'>;
}
declare module 'babel-preset-meteor/modern.js' {
  declare module.exports: $Exports<'babel-preset-meteor/modern'>;
}
