// flow-typed signature: 62fca2929d93cf2588a2c9c94a8cc8b1
// flow-typed version: <<STUB>>/eslint-import-resolver-meteor_v^0.4.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-meteor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-meteor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-meteor/test/imports/another-file' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-meteor/test/imports/client/client-test' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-meteor/test/imports/package-test/client/index' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-meteor/test/imports/package-test/plain-file' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-meteor/test/imports/package-test/server/index' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-meteor/test/imports/server/server-test' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-meteor/test/imports/test-file' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-meteor/test/paths' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-meteor/index' {
  declare module.exports: $Exports<'eslint-import-resolver-meteor'>;
}
declare module 'eslint-import-resolver-meteor/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-meteor'>;
}
declare module 'eslint-import-resolver-meteor/test/imports/another-file.js' {
  declare module.exports: $Exports<'eslint-import-resolver-meteor/test/imports/another-file'>;
}
declare module 'eslint-import-resolver-meteor/test/imports/client/client-test.js' {
  declare module.exports: $Exports<'eslint-import-resolver-meteor/test/imports/client/client-test'>;
}
declare module 'eslint-import-resolver-meteor/test/imports/package-test/client/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-meteor/test/imports/package-test/client/index'>;
}
declare module 'eslint-import-resolver-meteor/test/imports/package-test/plain-file.js' {
  declare module.exports: $Exports<'eslint-import-resolver-meteor/test/imports/package-test/plain-file'>;
}
declare module 'eslint-import-resolver-meteor/test/imports/package-test/server/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-meteor/test/imports/package-test/server/index'>;
}
declare module 'eslint-import-resolver-meteor/test/imports/server/server-test.js' {
  declare module.exports: $Exports<'eslint-import-resolver-meteor/test/imports/server/server-test'>;
}
declare module 'eslint-import-resolver-meteor/test/imports/test-file.js' {
  declare module.exports: $Exports<'eslint-import-resolver-meteor/test/imports/test-file'>;
}
declare module 'eslint-import-resolver-meteor/test/paths.js' {
  declare module.exports: $Exports<'eslint-import-resolver-meteor/test/paths'>;
}
