// flow-typed signature: 148520d91052a8288abd0763b1d0793c
// flow-typed version: <<STUB>>/eslint-plugin-meteor_v^5.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-meteor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-meteor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-meteor/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/audit-argument-checks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/eventmap-params' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/no-dom-lookup-on-created' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/no-session' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/no-template-lifecycle-assignments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/no-template-parent-data' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/no-zero-timeout' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/prefer-session-equals' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/prefix-eventmap-selectors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/scope-dom-lookups' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/rules/template-names' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/ast/getPropertyName' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/ast/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/ast/isFunction' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/ast/isMeteorCall' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/ast/isMeteorProp' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/ast/isTemplateProp' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/environment' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/executors/filterExecutorsByAncestors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/executors/getExecutors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/executors/getExecutorsByEnv' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/executors/getExecutorsFromTest' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/executors/invert' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/executors/isMeteorBlockOnlyTest' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/executors/sets' {
  declare module.exports: any;
}

declare module 'eslint-plugin-meteor/lib/util/values' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-meteor/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/index'>;
}
declare module 'eslint-plugin-meteor/lib/rules/audit-argument-checks.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/audit-argument-checks'>;
}
declare module 'eslint-plugin-meteor/lib/rules/eventmap-params.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/eventmap-params'>;
}
declare module 'eslint-plugin-meteor/lib/rules/no-dom-lookup-on-created.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/no-dom-lookup-on-created'>;
}
declare module 'eslint-plugin-meteor/lib/rules/no-session.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/no-session'>;
}
declare module 'eslint-plugin-meteor/lib/rules/no-template-lifecycle-assignments.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/no-template-lifecycle-assignments'>;
}
declare module 'eslint-plugin-meteor/lib/rules/no-template-parent-data.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/no-template-parent-data'>;
}
declare module 'eslint-plugin-meteor/lib/rules/no-zero-timeout.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/no-zero-timeout'>;
}
declare module 'eslint-plugin-meteor/lib/rules/prefer-session-equals.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/prefer-session-equals'>;
}
declare module 'eslint-plugin-meteor/lib/rules/prefix-eventmap-selectors.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/prefix-eventmap-selectors'>;
}
declare module 'eslint-plugin-meteor/lib/rules/scope-dom-lookups.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/scope-dom-lookups'>;
}
declare module 'eslint-plugin-meteor/lib/rules/template-names.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/rules/template-names'>;
}
declare module 'eslint-plugin-meteor/lib/util/ast/getPropertyName.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/ast/getPropertyName'>;
}
declare module 'eslint-plugin-meteor/lib/util/ast/index.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/ast/index'>;
}
declare module 'eslint-plugin-meteor/lib/util/ast/isFunction.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/ast/isFunction'>;
}
declare module 'eslint-plugin-meteor/lib/util/ast/isMeteorCall.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/ast/isMeteorCall'>;
}
declare module 'eslint-plugin-meteor/lib/util/ast/isMeteorProp.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/ast/isMeteorProp'>;
}
declare module 'eslint-plugin-meteor/lib/util/ast/isTemplateProp.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/ast/isTemplateProp'>;
}
declare module 'eslint-plugin-meteor/lib/util/environment.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/environment'>;
}
declare module 'eslint-plugin-meteor/lib/util/executors/filterExecutorsByAncestors.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/executors/filterExecutorsByAncestors'>;
}
declare module 'eslint-plugin-meteor/lib/util/executors/getExecutors.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/executors/getExecutors'>;
}
declare module 'eslint-plugin-meteor/lib/util/executors/getExecutorsByEnv.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/executors/getExecutorsByEnv'>;
}
declare module 'eslint-plugin-meteor/lib/util/executors/getExecutorsFromTest.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/executors/getExecutorsFromTest'>;
}
declare module 'eslint-plugin-meteor/lib/util/executors/invert.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/executors/invert'>;
}
declare module 'eslint-plugin-meteor/lib/util/executors/isMeteorBlockOnlyTest.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/executors/isMeteorBlockOnlyTest'>;
}
declare module 'eslint-plugin-meteor/lib/util/executors/sets.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/executors/sets'>;
}
declare module 'eslint-plugin-meteor/lib/util/values.js' {
  declare module.exports: $Exports<'eslint-plugin-meteor/lib/util/values'>;
}
