// flow-typed signature: 633bd2231e1934c3458b96dd1a4b80a2
// flow-typed version: <<STUB>>/indexof_v0.0.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'indexof'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'indexof' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'indexof/index' {
  declare module.exports: $Exports<'indexof'>;
}
declare module 'indexof/index.js' {
  declare module.exports: $Exports<'indexof'>;
}
