// flow-typed signature: 2e106755b0dd842723af0a9ae6ef3b00
// flow-typed version: <<STUB>>/intl-relativeformat_vhttps://github.com/Floriferous/intl-relativeformat/tarball/master/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'intl-relativeformat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'intl-relativeformat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'intl-relativeformat/custom' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/dist/intl-relativeformat-with-locales' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/dist/intl-relativeformat-with-locales.min' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/dist/intl-relativeformat' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/dist/intl-relativeformat.min' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/dist/locale-data/fr' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/Gruntfile' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/lib/core' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/lib/diff' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/lib/en' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/lib/es5' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/lib/locales' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/lib/main' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/src/core' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/src/diff' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/src/en' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/src/es5' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/src/main' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/tests/benchmark/format-moment-second' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/tests/benchmark/format-moment-year' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/tests/benchmark/format-one-second' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/tests/benchmark/format-one-year' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/tests/benchmark/new-instance' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/tests/benchmark/new-moment-instance' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/tests/browserify/app' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/tests/index' {
  declare module.exports: any;
}

declare module 'intl-relativeformat/tests/runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'intl-relativeformat/custom.js' {
  declare module.exports: $Exports<'intl-relativeformat/custom'>;
}
declare module 'intl-relativeformat/dist/intl-relativeformat-with-locales.js' {
  declare module.exports: $Exports<'intl-relativeformat/dist/intl-relativeformat-with-locales'>;
}
declare module 'intl-relativeformat/dist/intl-relativeformat-with-locales.min.js' {
  declare module.exports: $Exports<'intl-relativeformat/dist/intl-relativeformat-with-locales.min'>;
}
declare module 'intl-relativeformat/dist/intl-relativeformat.js' {
  declare module.exports: $Exports<'intl-relativeformat/dist/intl-relativeformat'>;
}
declare module 'intl-relativeformat/dist/intl-relativeformat.min.js' {
  declare module.exports: $Exports<'intl-relativeformat/dist/intl-relativeformat.min'>;
}
declare module 'intl-relativeformat/dist/locale-data/fr.js' {
  declare module.exports: $Exports<'intl-relativeformat/dist/locale-data/fr'>;
}
declare module 'intl-relativeformat/Gruntfile.js' {
  declare module.exports: $Exports<'intl-relativeformat/Gruntfile'>;
}
declare module 'intl-relativeformat/index' {
  declare module.exports: $Exports<'intl-relativeformat'>;
}
declare module 'intl-relativeformat/index.js' {
  declare module.exports: $Exports<'intl-relativeformat'>;
}
declare module 'intl-relativeformat/lib/core.js' {
  declare module.exports: $Exports<'intl-relativeformat/lib/core'>;
}
declare module 'intl-relativeformat/lib/diff.js' {
  declare module.exports: $Exports<'intl-relativeformat/lib/diff'>;
}
declare module 'intl-relativeformat/lib/en.js' {
  declare module.exports: $Exports<'intl-relativeformat/lib/en'>;
}
declare module 'intl-relativeformat/lib/es5.js' {
  declare module.exports: $Exports<'intl-relativeformat/lib/es5'>;
}
declare module 'intl-relativeformat/lib/locales.js' {
  declare module.exports: $Exports<'intl-relativeformat/lib/locales'>;
}
declare module 'intl-relativeformat/lib/main.js' {
  declare module.exports: $Exports<'intl-relativeformat/lib/main'>;
}
declare module 'intl-relativeformat/src/core.js' {
  declare module.exports: $Exports<'intl-relativeformat/src/core'>;
}
declare module 'intl-relativeformat/src/diff.js' {
  declare module.exports: $Exports<'intl-relativeformat/src/diff'>;
}
declare module 'intl-relativeformat/src/en.js' {
  declare module.exports: $Exports<'intl-relativeformat/src/en'>;
}
declare module 'intl-relativeformat/src/es5.js' {
  declare module.exports: $Exports<'intl-relativeformat/src/es5'>;
}
declare module 'intl-relativeformat/src/main.js' {
  declare module.exports: $Exports<'intl-relativeformat/src/main'>;
}
declare module 'intl-relativeformat/tests/benchmark/format-moment-second.js' {
  declare module.exports: $Exports<'intl-relativeformat/tests/benchmark/format-moment-second'>;
}
declare module 'intl-relativeformat/tests/benchmark/format-moment-year.js' {
  declare module.exports: $Exports<'intl-relativeformat/tests/benchmark/format-moment-year'>;
}
declare module 'intl-relativeformat/tests/benchmark/format-one-second.js' {
  declare module.exports: $Exports<'intl-relativeformat/tests/benchmark/format-one-second'>;
}
declare module 'intl-relativeformat/tests/benchmark/format-one-year.js' {
  declare module.exports: $Exports<'intl-relativeformat/tests/benchmark/format-one-year'>;
}
declare module 'intl-relativeformat/tests/benchmark/new-instance.js' {
  declare module.exports: $Exports<'intl-relativeformat/tests/benchmark/new-instance'>;
}
declare module 'intl-relativeformat/tests/benchmark/new-moment-instance.js' {
  declare module.exports: $Exports<'intl-relativeformat/tests/benchmark/new-moment-instance'>;
}
declare module 'intl-relativeformat/tests/browserify/app.js' {
  declare module.exports: $Exports<'intl-relativeformat/tests/browserify/app'>;
}
declare module 'intl-relativeformat/tests/index.js' {
  declare module.exports: $Exports<'intl-relativeformat/tests/index'>;
}
declare module 'intl-relativeformat/tests/runner.js' {
  declare module.exports: $Exports<'intl-relativeformat/tests/runner'>;
}
