// flow-typed signature: abff67c56019c424e6df351fa1c3c0ae
// flow-typed version: <<STUB>>/meteor-babel_v^7.0.0-beta.47/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'meteor-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'meteor-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'meteor-babel/cache' {
  declare module.exports: any;
}

declare module 'meteor-babel/modern-versions' {
  declare module.exports: any;
}

declare module 'meteor-babel/options' {
  declare module.exports: any;
}

declare module 'meteor-babel/plugins/async-await' {
  declare module.exports: any;
}

declare module 'meteor-babel/plugins/dynamic-import' {
  declare module.exports: any;
}

declare module 'meteor-babel/plugins/inline-node-env' {
  declare module.exports: any;
}

declare module 'meteor-babel/plugins/named-function-expressions' {
  declare module.exports: any;
}

declare module 'meteor-babel/plugins/sanitize-for-in-objects' {
  declare module.exports: any;
}

declare module 'meteor-babel/register' {
  declare module.exports: any;
}

declare module 'meteor-babel/runtime' {
  declare module.exports: any;
}

declare module 'meteor-babel/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'meteor-babel/cache.js' {
  declare module.exports: $Exports<'meteor-babel/cache'>;
}
declare module 'meteor-babel/index' {
  declare module.exports: $Exports<'meteor-babel'>;
}
declare module 'meteor-babel/index.js' {
  declare module.exports: $Exports<'meteor-babel'>;
}
declare module 'meteor-babel/modern-versions.js' {
  declare module.exports: $Exports<'meteor-babel/modern-versions'>;
}
declare module 'meteor-babel/options.js' {
  declare module.exports: $Exports<'meteor-babel/options'>;
}
declare module 'meteor-babel/plugins/async-await.js' {
  declare module.exports: $Exports<'meteor-babel/plugins/async-await'>;
}
declare module 'meteor-babel/plugins/dynamic-import.js' {
  declare module.exports: $Exports<'meteor-babel/plugins/dynamic-import'>;
}
declare module 'meteor-babel/plugins/inline-node-env.js' {
  declare module.exports: $Exports<'meteor-babel/plugins/inline-node-env'>;
}
declare module 'meteor-babel/plugins/named-function-expressions.js' {
  declare module.exports: $Exports<'meteor-babel/plugins/named-function-expressions'>;
}
declare module 'meteor-babel/plugins/sanitize-for-in-objects.js' {
  declare module.exports: $Exports<'meteor-babel/plugins/sanitize-for-in-objects'>;
}
declare module 'meteor-babel/register.js' {
  declare module.exports: $Exports<'meteor-babel/register'>;
}
declare module 'meteor-babel/runtime.js' {
  declare module.exports: $Exports<'meteor-babel/runtime'>;
}
declare module 'meteor-babel/util.js' {
  declare module.exports: $Exports<'meteor-babel/util'>;
}
