// flow-typed signature: 36ed310434fdcce064ed81ef68e38844
// flow-typed version: <<STUB>>/mocha-multi-reporters_v^1.1.7/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-multi-reporters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-multi-reporters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-multi-reporters/artifacts/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'mocha-multi-reporters/artifacts/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'mocha-multi-reporters/lib/MultiReporters' {
  declare module.exports: any;
}

declare module 'mocha-multi-reporters/tests/custom-external-config' {
  declare module.exports: any;
}

declare module 'mocha-multi-reporters/tests/custom-internal-reporter' {
  declare module.exports: any;
}

declare module 'mocha-multi-reporters/tests/lib/MultiReporters.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-multi-reporters/artifacts/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'mocha-multi-reporters/artifacts/coverage/lcov-report/prettify'>;
}
declare module 'mocha-multi-reporters/artifacts/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'mocha-multi-reporters/artifacts/coverage/lcov-report/sorter'>;
}
declare module 'mocha-multi-reporters/index' {
  declare module.exports: $Exports<'mocha-multi-reporters'>;
}
declare module 'mocha-multi-reporters/index.js' {
  declare module.exports: $Exports<'mocha-multi-reporters'>;
}
declare module 'mocha-multi-reporters/lib/MultiReporters.js' {
  declare module.exports: $Exports<'mocha-multi-reporters/lib/MultiReporters'>;
}
declare module 'mocha-multi-reporters/tests/custom-external-config.js' {
  declare module.exports: $Exports<'mocha-multi-reporters/tests/custom-external-config'>;
}
declare module 'mocha-multi-reporters/tests/custom-internal-reporter.js' {
  declare module.exports: $Exports<'mocha-multi-reporters/tests/custom-internal-reporter'>;
}
declare module 'mocha-multi-reporters/tests/lib/MultiReporters.test.js' {
  declare module.exports: $Exports<'mocha-multi-reporters/tests/lib/MultiReporters.test'>;
}
