// flow-typed signature: 3c46512e516265aa4c2affd51751b339
// flow-typed version: <<STUB>>/normalize-scss_v^7.0.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize-scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize-scss' {
  declare module.exports: any;
}
