// flow-typed signature: 3a8734dfcba3029d911a4ef3ddbefd53
// flow-typed version: <<STUB>>/postcss-flexbox_v^1.0.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-flexbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-flexbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-flexbox/flexbox-configs' {
  declare module.exports: any;
}

declare module 'postcss-flexbox/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-flexbox/flexbox-configs.js' {
  declare module.exports: $Exports<'postcss-flexbox/flexbox-configs'>;
}
declare module 'postcss-flexbox/index' {
  declare module.exports: $Exports<'postcss-flexbox'>;
}
declare module 'postcss-flexbox/index.js' {
  declare module.exports: $Exports<'postcss-flexbox'>;
}
declare module 'postcss-flexbox/test.js' {
  declare module.exports: $Exports<'postcss-flexbox/test'>;
}
