// flow-typed signature: ba1361b5916a7df1e0a0f8f68896f2fc
// flow-typed version: <<STUB>>/react-protected-mailto_v^1.0.3/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-protected-mailto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-protected-mailto' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-protected-mailto/dist/obfuscate' {
  declare module.exports: any;
}

declare module 'react-protected-mailto/src/obfuscate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-protected-mailto/dist/obfuscate.js' {
  declare module.exports: $Exports<'react-protected-mailto/dist/obfuscate'>;
}
declare module 'react-protected-mailto/src/obfuscate.js' {
  declare module.exports: $Exports<'react-protected-mailto/src/obfuscate'>;
}
