// flow-typed signature: 6b012582ba3a5dce27b9c728776e8589
// flow-typed version: <<STUB>>/react-intl_vhttps://github.com/Floriferous/react-intl/tarball/build/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl/dist/react-intl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/react-intl.min' {
  declare module.exports: any;
}

declare module 'react-intl/lib/index.es' {
  declare module.exports: any;
}

declare module 'react-intl/lib/index' {
  declare module.exports: any;
}

declare module 'react-intl/locale-data/fr' {
  declare module.exports: any;
}

declare module 'react-intl/locale-data/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl/dist/react-intl.js' {
  declare module.exports: $Exports<'react-intl/dist/react-intl'>;
}
declare module 'react-intl/dist/react-intl.min.js' {
  declare module.exports: $Exports<'react-intl/dist/react-intl.min'>;
}
declare module 'react-intl/lib/index.es.js' {
  declare module.exports: $Exports<'react-intl/lib/index.es'>;
}
declare module 'react-intl/lib/index.js' {
  declare module.exports: $Exports<'react-intl/lib/index'>;
}
declare module 'react-intl/locale-data/fr.js' {
  declare module.exports: $Exports<'react-intl/locale-data/fr'>;
}
declare module 'react-intl/locale-data/index.js' {
  declare module.exports: $Exports<'react-intl/locale-data/index'>;
}
