// flow-typed signature: 3b173290057092b0c51f8ce001103689
// flow-typed version: <<STUB>>/react-mounter_v^1.2.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mounter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mounter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mounter/dist/client' {
  declare module.exports: any;
}

declare module 'react-mounter/dist/index' {
  declare module.exports: any;
}

declare module 'react-mounter/dist/server' {
  declare module.exports: any;
}

declare module 'react-mounter/dist/utils' {
  declare module.exports: any;
}

declare module 'react-mounter/scripts/mocha_runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mounter/dist/client.js' {
  declare module.exports: $Exports<'react-mounter/dist/client'>;
}
declare module 'react-mounter/dist/index.js' {
  declare module.exports: $Exports<'react-mounter/dist/index'>;
}
declare module 'react-mounter/dist/server.js' {
  declare module.exports: $Exports<'react-mounter/dist/server'>;
}
declare module 'react-mounter/dist/utils.js' {
  declare module.exports: $Exports<'react-mounter/dist/utils'>;
}
declare module 'react-mounter/index' {
  declare module.exports: $Exports<'react-mounter'>;
}
declare module 'react-mounter/index.js' {
  declare module.exports: $Exports<'react-mounter'>;
}
declare module 'react-mounter/scripts/mocha_runner.js' {
  declare module.exports: $Exports<'react-mounter/scripts/mocha_runner'>;
}
