// flow-typed signature: 064e98ecfcd92e700f31e28a508dd156
// flow-typed version: <<STUB>>/require-main-filename_v^1.0.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'require-main-filename'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'require-main-filename' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'require-main-filename/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'require-main-filename/index' {
  declare module.exports: $Exports<'require-main-filename'>;
}
declare module 'require-main-filename/index.js' {
  declare module.exports: $Exports<'require-main-filename'>;
}
declare module 'require-main-filename/test.js' {
  declare module.exports: $Exports<'require-main-filename/test'>;
}
