// flow-typed signature: 8417b8ad1df67271234ddf37db65e258
// flow-typed version: <<STUB>>/tracker-component_v^1.3.21/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tracker-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tracker-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tracker-component/dist/browser' {
  declare module.exports: any;
}

declare module 'tracker-component/dist/browser.min' {
  declare module.exports: any;
}

declare module 'tracker-component/dist/index' {
  declare module.exports: any;
}

declare module 'tracker-component/dist/window_bind' {
  declare module.exports: any;
}

declare module 'tracker-component/scripts/mocha_runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tracker-component/dist/browser.js' {
  declare module.exports: $Exports<'tracker-component/dist/browser'>;
}
declare module 'tracker-component/dist/browser.min.js' {
  declare module.exports: $Exports<'tracker-component/dist/browser.min'>;
}
declare module 'tracker-component/dist/index.js' {
  declare module.exports: $Exports<'tracker-component/dist/index'>;
}
declare module 'tracker-component/dist/window_bind.js' {
  declare module.exports: $Exports<'tracker-component/dist/window_bind'>;
}
declare module 'tracker-component/index' {
  declare module.exports: $Exports<'tracker-component'>;
}
declare module 'tracker-component/index.js' {
  declare module.exports: $Exports<'tracker-component'>;
}
declare module 'tracker-component/scripts/mocha_runner.js' {
  declare module.exports: $Exports<'tracker-component/scripts/mocha_runner'>;
}
