// flow-typed signature: 266a171896b10b77fb19e665f0e61dae
// flow-typed version: <<STUB>>/uninstall_v0.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uninstall'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uninstall' {
  declare module.exports: any;
}
