export const LOTS_COLLECTION = 'lots';

export const LOT_TYPES = {
  BASEMENT: 'BASEMENT',
  PARKING_MOTORBIKE: 'PARKING_MOTORBIKE',
  PARKING_CAR: 'PARKING_CAR',
  PARKING_IN_A_ROW: 'PARKING_IN_A_ROW',
  PARKING_DISABLED: 'PARKING_DISABLED',
};

export const LOT_QUERIES = {
  LOTS: 'LOTS',
};
