export const PROMOTIONS_COLLECTION = 'promotions';

export const PROMOTION_TYPES = {
  CREDIT: 'CREDIT',
  SHARE: 'SHARE',
};

export const PROMOTION_STATUS = {
  CANCELLED: 'CANCELLED',
  FINISHED: 'FINISHED',
  OPEN: 'OPEN',
  PREPARATION: 'PREPARATION',
};

export const PROMOTION_QUERIES = {
  ADMIN_PROMOTIONS: 'ADMIN_PROMORIONS',
  APP_PROMOTION: 'APP_PROMOTION',
  PRO_PROMOTION: 'PRO_PROMOTION',
  PRO_PROMOTIONS: 'PRO_PROMOTIONS',
  PROMOTION_FILES: 'PROMOTION_FILES',
  PROMOTION_SEARCH: 'PROMOTION_SEARCH',
};
