export const PROMOTIONS_COLLECTION = 'promotions';

export const PROMOTION_TYPES = {
  SHARE: 'SHARE',
  CREDIT: 'CREDIT',
};

export const PROMOTION_STATUS = {
  PREPARATION: 'PREPARATION',
  OPEN: 'OPEN',
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED',
};
