defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/openjdk:8-jdk-browsers


version: 2
jobs:
  install_meteor:
    <<: *defaults
    steps:
      - run:
          name: Create a file
          command: touch hello.txt
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - app
  use_meteor:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: List files
          command: ls


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install_meteor
      - use_meteor:
          requires:
            - install_meteor
