// Look in the `FeatureService` file at the `featureMap`
// to see how these toggle points impact the system
export const TOGGLE_POINTS = {
  WIDGET1_CONTINUE_BUTTON: 'WIDGET1_CONTINUE_BUTTON',
  STRIPPED_LITE_VERSION_UI: 'STRIPPED_LITE_VERSION_UI',
  ROUTES_CONFIG_STRIPPED_IN_LITE_VERSION:
    'ROUTES_CONFIG_STRIPPED_IN_LITE_VERSION',
  ROUTES_NOT_PRODUCTION_READY: 'ROUTES_NOT_PRODUCTION_READY',
};
