export const TOGGLE_POINTS = {
  WIDGET1_CONTINUE_BUTTON: 'WIDGET1_CONTINUE_BUTTON',
  LITE_VERSION_OFF: 'LITE_VERSION_OFF',
  ROUTES_CONFIG_UNUSED_IN_LITE_VERSION: 'ROUTES_CONFIG_UNUSED_IN_LITE_VERSION',
  BASE_ROUTER_HAS_LOGIN: 'BASE_ROUTER_HAS_LOGIN',
};
