export const TOGGLE_POINTS = {
  WIDGET1_CONTINUE_BUTTON: 'WIDGET1_CONTINUE_BUTTON',
  STRIPPED_LITE_VERSION_UI: 'STRIPPED_LITE_VERSION_UI',
  ROUTES_CONFIG_STRIPPED_IN_LITE_VERSION: 'ROUTES_CONFIG_STRIPPED_IN_LITE_VERSION',
  BASE_ROUTER_HAS_LOGIN: 'BASE_ROUTER_HAS_LOGIN',
};
