export const CHECKLISTS_COLLECTION = 'checklists';

export const CHECKLIST_ITEM_STATUS = {
  TO_DO: 'TO_DO',
  VALIDATED: 'VALIDATED',
  VALIDATED_BY_ADMIN: 'VALIDATED_BY_ADMIN',
};

export const CHECKLIST_QUERIES = {
  LOAN_CHECKLISTS: 'LOAN_CHECKLISTS',
};

export const CHECKLIST_ITEM_ACCESS = {
  USER: 'user',
  ADMIN: 'admin',
};
