export const BORROWERS_COLLECTION = 'borrowers';

export const RESIDENCY_PERMIT = {
  B: 'b',
  C: 'c',
  CI: 'ci',
  F: 'f',
  G: 'g',
  L: 'l',
  N: 'n',
  S: 's',
  NONE: 'none',
};

export const GENDER = {
  M: 'M',
  F: 'F',
  OTHER: 'OTHER',
};

export const CIVIL_STATUS = {
  MARRIED: 'MARRIED',
  SINGLE: 'SINGLE',
  PACSED: 'PACSED',
  DIVORCED: 'DIVORCED',
};

export const OTHER_FORTUNE = {
  ART: 'ART',
  CARS: 'CARS',
  BOATS: 'BOATS',
  AIRPLANES: 'AIRPLANES',
  JEWELRY: 'JEWELRY',
};

export const OTHER_INCOME = {
  WELFARE: 'WELFARE',
  PENSION: 'PENSION',
  RENT: 'RENT',
  REAL_ESTATE: 'REAL_ESTATE',
  INVESTMENT: 'INVESTMENT',
  OTHER: 'OTHER',
};

export const EXPENSES = {
  LEASING: 'LEASING',
  RENT: 'RENT',
  PERSONAL_LOAN: 'PERSONAL_LOAN',
  MORTGAGE_LOAN: 'MORTGAGE_LOAN',
  PENSIONS: 'PENSIONS',
  OTHER: 'OTHER',
};

export const REAL_ESTATE = {
  PRIMARY: 'PRIMARY',
  SECONDARY: 'SECONDARY',
  INVESTMENT: 'INVESTMENT',
};

export const BORROWER_QUERIES = {
  ADMIN_BORROWERS: 'ADMIN_BORROWERS',
  BORROWER_ASSIGNED_TO: 'BORROWER_ASSIGNED_TO',
  SIDENAV_BORROWERS: 'SIDENAV_BORROWERS',
};
