export const ORGANISATIONS_COLLECTION = 'organisations';
export const ORGANISATION_TYPES = {
  BANK: 'BANK',
  INSURANCE: 'INSURANCE',
  PRIVATE_BANK: 'PRIVATE_BANK',
};
export const ORGANISATION_QUERIES = {
  ADMIN_ORGANISATIONS: 'ADMIN_ORGANISATIONS',
  FILES: 'FILES',
};
