export const ORGANISATIONS_COLLECTION = 'organisations';

export const ORGANISATION_TYPES = {
  BANK: 'BANK',
  INSURANCE: 'INSURANCE',
  PRIVATE_BANK: 'PRIVATE_BANK',
  REAL_ESTATE_BROKER: 'REAL_ESTATE_BROKER',
  NOTARY_OFFICE: 'NOTARY_OFFICE',
  CONSTRUCTION_COMPANY: 'CONSTRUCTION_COMPANY',
  DEVELOPER: 'DEVELOPER',
  ARCHITECT: 'ARCHITECT',
  OTHER: 'OTHER',
};

export const ORGANISATION_QUERIES = {
  ADMIN_ORGANISATIONS: 'ADMIN_ORGANISATIONS',
  FILES: 'FILES',
  ORGANISATION_SEARCH: 'ORGANISATION_SEARCH',
  PRO_ORGANISATION: 'PRO_ORGANISATION',
  USER_ORGANISATIONS: 'USER_ORGANISATIONS',
};

export const ORGANISATION_FEATURES = {
  LENDER: 'LENDER',
  PRO: 'PRO',
};

export const ORGANISATION_TAGS = {
  CH_PREMIUM: 'CH_PREMIUM',
  CH_RETAIL: 'CH_RETAIL',
  FR_RETAIL: 'FR_RETAIL',
  FR_PREMIUM: 'FR_PREMIUM',
  YACHTING: 'YACHTING',
  HELICOPTERS_LEASING: 'HELICOPTERS_LEASING',
  LBO: 'LBO',
};
