import React from 'react';

const getPropertyArray = (loanRequest, borrowers) => {
  const r = loanRequest;

  return [
    {
      type: 'textInput',
      money: true,
      label: "Prix d'Achat",
      placeholder: "CHF 500'000",
      id: 'property.value',
      currentValue: r.property.value,
    },
    {
      type: 'textInput',
      money: true,
      label: 'Travaux de plus-value',
      placeholder: "CHF 50'000",
      id: 'property.propertyWork',
      currentValue: r.property.propertyWork,
      required: false,
    },
    {
      type: 'radioInput',
      label: 'Utilisation de la propriété',
      id: 'property.usageType',
      currentValue: r.property.usageType,
      options: [
        {
          id: 'primary',
          label: 'Résidence Principale',
        },
        {
          id: 'secondary',
          label: 'Résidence Secondaire',
        },
        {
          id: 'investment',
          label: "Bien d'investissement",
        },
      ],
    },
    {
      type: 'radioInput',
      label: 'Type de bien immobilier',
      options: [
        {
          id: 'villa',
          label: 'Villa',
        },
        {
          id: 'flat',
          label: 'Appartement',
        },
      ],
      id: 'property.style',
      currentValue: r.property.style,
    },
    {
      type: 'conditionalInput',
      conditionalTrueValue: 'other',
      showCondition: borrowers.length > 1 &&
        r.general.purchaseType === 'refinancing',
      inputs: [
        {
          type: 'radioInput',
          label: 'Qui est le propriétaire actuel?',
          options: [
            { id: '0', label: borrowers[0].firstName || 'Emprunteur 1' },
            {
              id: '1',
              label: (borrowers[1] && borrowers[1].firstName) || 'Emprunteur 2',
            },
            { id: 'both', label: 'Les Deux' },
            { id: 'other', label: 'Autre' },
          ],
          id: 'general.currentOwner',
          currentValue: r.general.currentOwner,
        },
        {
          type: 'textInput',
          label: 'Autre propriétaire',
          placeholder: '',
          id: 'general.otherOwner',
          currentValue: r.general.otherOwner,
        },
      ],
    },
    {
      type: 'conditionalInput',
      conditionalTrueValue: 'other',
      showCondition: borrowers.length > 1 &&
        r.general.purchaseType !== 'refinancing',
      inputs: [
        {
          type: 'radioInput',
          label: 'Qui sera le propriétaire du bien immobilier?',
          options: [
            { id: '0', label: borrowers[0].firstName || 'Emprunteur 1' },
            {
              id: '1',
              label: (borrowers[1] && borrowers[1].firstName) || 'Emprunteur 2',
            },
            { id: 'both', label: 'Les Deux' },
            { id: 'other', label: 'Autre' },
          ],
          id: 'general.futureOwner',
          currentValue: r.general.futureOwner,
        },
        {
          type: 'textInput',
          label: 'Autre propriétaire',
          placeholder: '',
          id: 'general.otherOwner',
          currentValue: r.general.otherOwner,
        },
      ],
    },
    {
      type: 'h3',
      text: 'Adresse du bien immobilier',
    },
    {
      type: 'textInput',
      label: 'Adresse 1',
      placeholder: 'Rue des Champs 7',
      id: 'property.address1',
      currentValue: r.property.address1,
    },
    {
      type: 'textInput',
      label: 'Adresse 2',
      placeholder: '',
      id: 'property.address2',
      currentValue: r.property.address2,
      required: false,
    },
    {
      type: 'textInput',
      number: true,
      label: 'Code Postal',
      placeholder: '1200',
      id: 'property.zipCode',
      currentValue: r.property.zipCode,
    },
    {
      type: 'textInput',
      label: 'Localité',
      placeholder: 'Genève',
      id: 'property.city',
      currentValue: r.property.city,
    },
    {
      type: 'h3',
      text: 'Détails du bien',
    },
    {
      type: 'textInput',
      number: true,
      label: 'Année de construction',
      placeholder: '2005',
      id: 'property.constructionYear',
      currentValue: r.property.constructionYear,
    },
    {
      type: 'textInput',
      number: true,
      label: 'Année de rénovation',
      placeholder: '2010',
      id: 'property.renovationYear',
      currentValue: r.property.renovationYear,
      required: false,
      info: 'Seulement si la propriété a été rénovée',
    },
    {
      type: 'textInput',
      number: true,
      label: <span>Surface du terrain en m<sup>2</sup> *</span>,
      placeholder: '250',
      id: 'property.landArea',
      currentValue: r.property.landArea,
      showCondition: r.property.style === 'villa',
    },
    {
      type: 'textInput',
      number: true,
      label: <span>Surface habitable en m<sup>2</sup> *</span>,
      placeholder: '150',
      id: 'property.insideArea',
      currentValue: r.property.insideArea,
    },
    {
      type: 'textInput',
      number: true,
      label: <span>Surface des balcons en m<sup>2</sup> *</span>,
      placeholder: '20',
      id: 'property.balconyArea',
      currentValue: r.property.balconyArea,
    },
    {
      type: 'textInput',
      number: true,
      label: <span>Surface des terrasses en m<sup>2</sup> *</span>,
      placeholder: '40',
      id: 'property.terraceArea',
      currentValue: r.property.terraceArea,
    },
    {
      type: 'textInput',
      number: true,
      label: <span>Volume/Cubage en m<sup>3</sup> *</span>,
      placeholder: '1000',
      id: 'property.volume',
      currentValue: r.property.volume,
      showCondition: r.property.style === 'villa',
    },
    {
      type: 'textInput',
      label: 'Type de cubage',
      placeholder: 'SIA',
      id: 'property.volumeNorm',
      currentValue: r.property.volumeNorm,
      showCondition: r.property.style === 'villa',
    },
    {
      type: 'textInput',
      number: true,
      label: 'Nb. de chambres',
      placeholder: '3.5',
      id: 'property.roomCount',
      currentValue: r.property.roomCount,
      info: 'Chambres à coucher',
    },
    {
      type: 'textInput',
      number: true,
      label: 'Nb. de salles de bain',
      placeholder: '1',
      id: 'property.bathroomCount',
      currentValue: r.property.bathroomCount,
      info: 'Salles de bains ou salles d’eau (respectivement avec baignoire ou douche)',
    },
    {
      type: 'textInput',
      number: true,
      label: 'Nb. de WC',
      placeholder: '1',
      id: 'property.toiletCount',
      currentValue: r.property.toiletCount,
    },
    {
      type: 'textInput',
      number: true,
      label: 'Places de parc intérieur',
      placeholder: '1',
      id: 'property.parking.inside',
      currentValue: r.property.parking.inside,
    },
    {
      type: 'textInput',
      number: true,
      label: 'Box de parking',
      placeholder: '1',
      id: 'property.parking.box',
      currentValue: r.property.parking.box,
    },
    {
      type: 'textInput',
      number: true,
      label: 'Places de parc extérieur couvertes',
      placeholder: '1',
      id: 'property.parking.outsideCovered',
      currentValue: r.property.parking.outsideCovered,
    },
    {
      type: 'textInput',
      number: true,
      label: 'Places de parc extérieur non-couvertes',
      placeholder: '1',
      id: 'property.parking.outsideNotCovered',
      currentValue: r.property.parking.outsideNotCovered,
    },
    {
      type: 'radioInput',
      label: 'Est-ce une construction Minergie?',
      options: [{ id: true, label: 'Oui' }, { id: false, label: 'Non' }],
      id: 'property.minergie',
      currentValue: r.property.minergie,
    },
    {
      type: 'conditionalInput',
      conditionalTrueValue: true,
      showCondition: r.property.style === 'villa',
      inputs: [
        {
          type: 'radioInput',
          label: 'Est-ce une copropriété',
          options: [{ id: true, label: 'Oui' }, { id: false, label: 'Non' }],
          id: 'property.isCoproperty',
          currentValue: r.property.isCoproperty,
        },
        {
          type: 'textInput',
          number: true,
          label: 'Répartition du bien au sein de la copropriété',
          placeholder: '0.125',
          id: 'property.copropertyPercentage',
          currentValue: r.property.copropertyPercentage,
          info: 'Au millième',
        },
      ],
    },
    {
      type: 'textInput',
      decimal: true,
      label: 'Répartition du bien au sein de la copropriété',
      placeholder: '0.125',
      id: 'property.copropertyPercentage',
      currentValue: r.property.copropertyPercentage,
      showCondition: r.property.style === 'flat',
      info: 'Au millième',
    },
    {
      type: 'h3',
      text: 'Qualité et Emplacement',
    },
    {
      type: 'radioInput',
      label: "Type d'emplacement au sein de la commune",
      options: [
        { id: 0, label: 'Mauvais' },
        { id: 1, label: 'Moyen' },
        { id: 2, label: 'Bon' },
        { id: 3, label: 'Très Bon' },
      ],
      id: 'property.cityPlacementQuality',
      currentValue: r.property.cityPlacementQuality,
    },
    {
      type: 'radioInput',
      label: "Emplacement dans l'immeuble",
      options: [
        { id: 0, label: 'Mauvais' },
        { id: 1, label: 'Moyen' },
        { id: 2, label: 'Bon' },
        { id: 3, label: 'Très Bon' },
      ],
      id: 'property.buildingPlacementQuality',
      currentValue: r.property.buildingPlacementQuality,
      showCondition: r.property.style === 'flat',
    },
    {
      type: 'radioInput',
      label: 'Condition d’entretien du bâtiment',
      options: [
        { id: 0, label: 'Mauvais' },
        { id: 1, label: 'Moyen' },
        { id: 2, label: 'Bon' },
        { id: 3, label: 'Très Bon' },
      ],
      id: 'property.buildingQuality',
      currentValue: r.property.buildingQuality,
    },
    {
      type: 'radioInput',
      label: 'Condition d’entretien de l’appartement',
      options: [
        { id: 0, label: 'Mauvais' },
        { id: 1, label: 'Moyen' },
        { id: 2, label: 'Bon' },
        { id: 3, label: 'Très Bon' },
      ],
      id: 'property.flatQuality',
      currentValue: r.property.flatQuality,
      showCondition: r.property.style === 'flat',
    },
    {
      type: 'radioInput',
      label: 'Qualité des matériaux',
      options: [
        { id: 0, label: 'Mauvais' },
        { id: 1, label: 'Moyen' },
        { id: 2, label: 'Bon' },
        { id: 3, label: 'Très Bon' },
      ],
      id: 'property.materialsQuality',
      currentValue: r.property.materialsQuality,
    },
    {
      type: 'textInputLarge',
      label: 'Autres informations',
      placeholder: 'Aménagements extérieurs, piscine, jardins, cabanons, annexes, sous-sols utiles,...',
      id: 'property.other',
      currentValue: r.property.other,
      rows: 3,
      required: false,
    },
  ];
};

export default getPropertyArray;
