name: mup-parallel
root: ./
pre_window: bash
on_project_exit: >-
  tmux kill-session -t mup-parallel
windows:
  - deploy:
      layout: tiled
      panes:
        - instructions:
            - tmux set pane-border-status bottom
            - tmux select-pane -t 0 -T Instructions
            - node ./utils/tmux-instructions.js

        
        - admin-prod:
            - tmux set pane-border-status bottom
            - export NPM_CONFIG_PREFIX=""
            
            - (cd ../scripts && bash setup-microservice.sh admin)
            
            - tmux select-pane -t 1 -T "deploy - admin"
            - cd ./prod
            - METEOR_ALLOW_SUPERUSER=true EPOTEK_RUN_PARALLEL=true /Users/flo/dev/epotek/node_modules/.bin/mup --config admin.mup.js deploy || echo "FAILED"
            - echo "DONE"

           
        - backend-prod:
            - tmux set pane-border-status bottom
            - export NPM_CONFIG_PREFIX=""
            
            - (cd ../scripts && bash setup-microservice.sh backend)
            
            - tmux select-pane -t 2 -T "deploy - backend"
            - cd ./prod
            - METEOR_ALLOW_SUPERUSER=true EPOTEK_RUN_PARALLEL=true /Users/flo/dev/epotek/node_modules/.bin/mup --config backend.mup.js deploy || echo "FAILED"
            - echo "DONE"

           
        - www-prod:
            - tmux set pane-border-status bottom
            - export NPM_CONFIG_PREFIX=""
            
            - (cd ../scripts && bash setup-microservice.sh www)
            
            - tmux select-pane -t 3 -T "deploy - www"
            - cd ./prod
            - METEOR_ALLOW_SUPERUSER=true EPOTEK_RUN_PARALLEL=true /Users/flo/dev/epotek/node_modules/.bin/mup --config www.mup.js deploy || echo "FAILED"
            - echo "DONE"

           
        - pro-prod:
            - tmux set pane-border-status bottom
            - export NPM_CONFIG_PREFIX=""
            
            - (cd ../scripts && bash setup-microservice.sh pro)
            
            - tmux select-pane -t 4 -T "deploy - pro"
            - cd ./prod
            - METEOR_ALLOW_SUPERUSER=true EPOTEK_RUN_PARALLEL=true /Users/flo/dev/epotek/node_modules/.bin/mup --config pro.mup.js deploy || echo "FAILED"
            - echo "DONE"

           
