export const ORGANIZATIONS_COLLECTION = 'organizations';
export const ORGANIZATION_TYPES = {
  BANK: 'BANK',
  INSURANCE: 'INSURANCE',
  PRIVATE_BANK: 'PRIVATE_BANK',
};
export const ORGANIZATION_QUERIES = {
  ADMIN_ORGANIZATIONS: 'ADMIN_ORGANIZATIONS',
  FILES: 'FILES',
};
