[Settings]
  ID = "27af9c2d-46dc-42c1-bed4-6d0feca2dd34"

[Build]
  Publish = ""
  Functions = ""

[[redirects]]
  from = "/about"
  to = "/fr/a-propos"

[[redirects]]
  from = "/contact"
  to = "/fr/accueil"

[[redirects]]
  from = "/interests"
  to = "/fr/taux-hypothecaires"

[[redirects]]
  from = "/careers"
  to = "/fr/accueil"

[[redirects]]
  from = "/faq"
  to = "/fr/faq"

[[redirects]]
  from = "/blog"
  to = "/fr/blog"

[[redirects]]
  from = "/blog/*"
  to = "/fr/blog"

[[redirects]]
  from = "/"
  to = "/fr/accueil"