export const PROMOTION_OPTIONS_COLLECTION = 'promotionOptions';

export const PROMOTION_OPTION_STATUS = {
  TRIAL: 'TRIAL',
  WANT_TO_BUY: 'WANT_TO_BUY',
};

export const PROMOTION_OPTION_QUERIES = {
  APP_PROMOTION_OPTION: 'APP_PROMOTION_OPTION',
  PRO_PROMOTION_OPTIONS: 'PRO_PROMOTION_OPTIONS',
};
