export const ACTIVITIES_COLLECTION = 'activities';

export const ACTIVITY_QUERIES = {
  ADMIN_ACTIVITIES: 'ADMIN_ACTIVITIES',
};

export const ACTIVITY_TYPES = {
  EMAIL: 'EMAIL',
  EVENT: 'EVENT',
  MAIL: 'MAIL',
  PHONE: 'PHONE',
  OTHER: 'OTHER',
};

export const ACTIVITY_EVENT_METADATA = {
  CREATED: 'CREATED',
  REMOVE_LOAN_FROM_PROMOTION: 'REMOVE_LOAN_FROM_PROMOTION',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  EMAIL_SENT: 'EMAIL_SENT',
  USER_PASSWORD_SET: 'USER_PASSWORD_SET',
  USER_FIRST_CONNECTION: 'USER_FIRST_CONNECTION',
  USER_CHANGE_ASSIGNEE: 'USER_CHANGE_ASSIGNEE',
  USER_CHANGE_REFERRAL: 'USER_CHANGE_REFERRAL',
  USER_CHANGE_EMAIL: 'USER_CHANGE_EMAIL',
  USER_VERIFIED_EMAIL: 'USER_VERIFIED_EMAIL',
  LOAN_CHANGE_STATUS: 'LOAN_CHANGE_STATUS',
  LOAN_DISBURSEMENT_DATE: 'LOAN_DISBURSEMENT_DATE',
  NEW_LOAN_ASSIGNEES: 'NEW_LOAN_ASSIGNEES',
};
