export const ACTIVITIES_COLLECTION = 'activities';

export const ACTIVITY_QUERIES = {
  ADMIN_ACTIVITIES: 'ADMIN_ACTIVITIES',
};

export const ACTIVITY_TYPES = {
  EMAIL: 'EMAIL',
  EVENT: 'EVENT',
  PHONE: 'PHONE',
  SERVER: 'SERVER',
  OTHER: 'OTHER',
};

export const ACTIVITY_SECONDARY_TYPES = {
  CREATED: 'CREATED',
  REMOVE_LOAN_FROM_PROMOTION: 'REMOVE_LOAN_FROM_PROMOTION',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  EMAIL_SENT: 'EMAIL_SENT',
};
