export const REVENUES_COLLECTION = 'revenues';

export const REVENUE_QUERIES = {
  ADMIN_REVENUES: 'ADMIN_REVENUES',
};

export const REVENUE_TYPES = {
  INSURANCE: 'INSURANCE',
  MORTGAGE: 'MORTGAGE',
  FEE: 'FEE',
  OTHER: 'OTHER',
};

const REVENUE_TYPES_INSURANCE = {
  DEATH_3A: 'DEATH_3A',
  DEATH_3B: 'DEATH_3B',
  INCOME_PROTECTION_3A: 'INCOME_PROTECTION_3A',
  INCOME_PROTECTION_3B: 'INCOME_PROTECTION_3B',
  LIFE_3A: 'LIFE_3A',
  LIFE_3B: 'LIFE_3B',
};

export const REVENUE_SECONDARY_TYPES = {
  ...REVENUE_TYPES_INSURANCE,
};

export const REVENUE_STATUS = {
  EXPECTED: 'EXPECTED',
  CLOSED: 'CLOSED',
};

export const COMMISSION_STATUS = {
  PAID: 'PAID',
  TO_BE_PAID: 'TO_BE_PAID',
};
