export const REVENUES_COLLECTION = 'revenues';

export const REVENUE_QUERIES = {
  PRO_REVENUES: 'PRO_REVENUES',
};

export const REVENUE_TYPES = {
  INSURANCE: 'INSURANCE',
  MORTGAGE: 'MORTGAGE',
  FEE: 'FEE',
  OTHER: 'OTHER',
};

export const REVENUE_STATUS = {
  EXPECTED: 'EXPECTED',
  CLOSED: 'CLOSED',
};

export const COMMISSION_STATUS = {
  PAID: 'PAID',
  TO_BE_PAID: 'TO_BE_PAID',
};

export const PRO_COMMISSION_STATUS = {
  WAITING_FOR_REVENUE: 'WAITING_FOR_REVENUE',
  COMMISSION_TO_PAY: 'COMMISSION_TO_PAY',
  COMMISSION_PAID: 'COMMISSION_PAID',
};
