export const REVENUES_COLLECTION = 'revenues';

export const REVENUE_QUERIES = {
  ADMIN_REVENUES: 'ADMIN_REVENUES',
};

export const REVENUE_TYPES = {
  INSURANCE: 'INSURANCE',
  MORTGAGE: 'MORTGAGE',
  FEE: 'FEE',
  OTHER: 'OTHER',
};

export const REVENUE_STATUS = {
  EXPECTED: 'EXPECTED',
  CLOSED: 'CLOSED',
};

export const COMMISSION_STATUS = {
  PAID: 'PAID',
  TO_BE_PAID: 'TO_BE_PAID',
};
