import {
  RESIDENCE_TYPE,
  PROPERTY_TYPE,
  MINERGIE_CERTIFICATE,
  HOUSE_TYPE,
  FLAT_TYPE,
  VOLUME_NORM,
  AREA_NORM,
} from 'core/api/properties/propertyConstants';

export const WUEST_PROPERTY_TYPE = {
  HOUSE: PROPERTY_TYPE.HOUSE,
  FLAT: PROPERTY_TYPE.FLAT,
};
export const WUEST_HED_METHOD = {
  SFH: 'HED_SFH',
  CON: 'HED_CON',
};

export const WUEST_RESIDENCE_TYPE = {
  MAIN: RESIDENCE_TYPE.MAIN,
  SECOND: RESIDENCE_TYPE.SECOND,
  INVESTMENT: RESIDENCE_TYPE.MAIN,
};

export const WUEST_MINERGIE_CERTIFICATE = {
  WITHOUT: MINERGIE_CERTIFICATE.WITHOUT,
  P: MINERGIE_CERTIFICATE.P,
  ECO: MINERGIE_CERTIFICATE.ECO,
  P_ECO: MINERGIE_CERTIFICATE.P_ECO,
  OTHER: MINERGIE_CERTIFICATE.OTHER,
};

export const WUEST_HOUSE_TYPE = {
  DETACHED: HOUSE_TYPE.DETACHED,
  ATTACHED_END: HOUSE_TYPE.ATTACHED_END,
  ATTACHED_MID: HOUSE_TYPE.ATTACHED_MID,
};

export const WUEST_FLAT_TYPE = {
  SINGLE_FLOOR: FLAT_TYPE.SINGLE_FLOOR,
  DUPLEX: FLAT_TYPE.DUPLEX,
  PENTHOUSE: FLAT_TYPE.PENTHOUSE,
  PENTHOUSE_DUPLEX: FLAT_TYPE.PENTHOUSE_DUPLEX,
  GROUND_FLOOR: FLAT_TYPE.GROUND_FLOOR,
};

// TODO: check size of array
export const WUEST_FLOOR_NUMBER = [
  'GROUND_FLOOR',
  'FIRST_FLOOR',
  'SECOND_FLOOR',
  'THIRD_FLOOR',
  'FOURTH_FLOOR',
  'FIFTH_FLOOR',
  'SIXTH_FLOOR',
  'SEVENTH_FLOOR',
  'EIGHTH_FLOOR',
  'NINTH_FLOOR',
  'TENTH_FLOOR',
  'ELEVENTH_FLOOR',
  'TWELVTH_FLOOR',
  'THIRTEENTH_FLOOR',
  'FOURTEETNH_FLOOR',
  'FIFTEENTH_FLOOR',
  'SIXTEENTH_FLOOR',
  'SEVENTEENTH_FLOOR',
  'EIGHTEENTH_FLOOR',
  'NINETEENTH_FLOOR',
  'TWENTIETH_FLOOR',
];

export const WUEST_VOLUME_TYPE = {
  SIA_416: VOLUME_NORM.SIA_416,
  SIA_116: VOLUME_NORM.SIA_116,
  BIC: VOLUME_NORM.BIC,
};

export const WUEST_AREA_TYPE = {
  NET: AREA_NORM.NET,
  GROSS: AREA_NORM.GROSS,
};

export const WUEST_QUALITY = {
  CONDITION: {
    NEEDS_RENNOVATION: 1,
    INTACT: 3,
    EXCELLENT: 5,
  },
  STANDARD: {
    UNSATISFACTORY: 1,
    AVERAGE: 3,
    HIGH: 4.5,
  },
  SITUATION: {
    BAD: 1.5,
    AVERAGE: 2,
    GOOD: 4,
  },
};

export const WUEST_JSON_DATA_STRUCTURE = {
  embedded: [
    { rel: 'valueCorrections' },
    { rel: 'objectData', value: { embedded: [{ rel: 'buildings' }] } },
    { rel: 'qualityProfile' },
  ],
};

export const WUEST_ERRORS = {
  NO_PROPERTY_DATA_PROVIDED: 'NO_PROPERTY_DATA_PROVIDED',
  NO_PROPERTY_FOUND: 'NO_PROPERTY_FOUND',
  NO_FLOOR_NUMBER_PROVIDED: 'NO_FLOOR_NUMBER_PROVIDED',
  INVALID_FLOOR_NUMBER: 'INVALID_FLOOR_NUMBER',
  NO_ADDRESS_PROVIDED: 'NO_ADDRESS_PROVIDED',
  NO_RESIDENCE_TYPE_PROVIDED: 'NO_RESIDENCE_TYPE_PROVIDED',
  INVALID_RESIDENCE_TYPE: 'INVALID_RESIDENCE_TYPE',
  NO_ADDRESS_LINE_1_PROVIDED: 'NO_ADDRESS_LINE_1_PROVIDED',
  NO_ZIPCODE_PROVIDED: 'NO_ZIPCODE_PROVIDED',
  NO_CITY_PROVIDED: 'NO_CITY_PROVIDED',
  NO_COUNTRY_PROVIDED: 'NO_COUNTRY_PROVIDED',
  NO_HOUSE_TYPE_PROVIDED: 'NO_HOUSE_TYPE_PROVIDED',
  INVALID_HOUSE_TYPE: 'INVALID_HOUSE_TYPE',
  NO_BUILDING_VOLUME_PROVIDED: 'NO_BUILDING_VOLUME_PROVIDED',
  NO_BUILDING_VOLUME_VALUE_PROVIDED: 'NO_BUILDING_VOLUME_VALUE_PROVIDED',
  NO_BUILDING_VOLUME_TYPE_PROVIDED: 'NO_BUILDING_VOLUME_TYPE_PROVIDED',
  INVALID_BUILDING_VOLUME_TYPE: 'INVALID_BUILDING_VOLUME_TYPE',
  NO_LANDPLOT_AREA_PROVIDED: 'NO_LANDPLOT_AREA_PROVIDED',
  NO_PARKING_PROVIDED: 'NO_PARKING_PROVIDED',
  NO_INSIDE_PARKING_PROVIDED: 'NO_INSIDE_PARKING_PROVIDED',
  NO_OUTSIDE_PARKING_PROVIDED: 'NO_OUTSIDE_PARKING_PROVIDED',
  NO_NUMBER_OF_ROOMS_PROVIDED: 'NO_NUMBER_OF_ROOMS_PROVIDED',
  NO_CONSTRUCTION_YEAR_PROVIDED: 'NO_CONSTRUCTION_YEAR_PROVIDED',
  NO_MINERGIE_CERTIFICATE_PROVIDED: 'NO_MINERGIE_CERTIFICATE_PROVIDED',
  INVALID_MINERGIE_CERTIFICATE: 'INVALID_MINERGIE_CERTIFICATE',
  NO_QUALITY_PROFILE_PROVIDED: 'NO_QUALITY_PROFILE_PROVIDED',
  NO_QUALITY_PROFILE_STANDARD_PROVIDED: 'NO_QUALITY_PROFILE_STANDARD_PROVIDED',
  NO_QUALITY_PROFILE_CONDITION_PROVIDED:
    'NO_QUALITY_PROFILE_CONDITION_PROVIDED',
  NO_QUALITY_PROFILE_SITUATION_PROVIDED:
    'NO_QUALITY_PROFILE_SITUATION_PROVIDED',
  INVALID_QUALITY_PROFILE_STANDARD: 'INVALID_QUALITY_PROFILE_STANDARD',
  INVALID_QUALITY_PROFILE_CONDITION: 'INVALID_QUALITY_PROFILE_CONDITION',
  INVALID_QUALITY_PROFILE_SITUATION: 'INVALID_QUALITY_PROFILE_SITUATION',
  NO_FLAT_TYPE_PROVIDED: 'NO_FLAT_TYPE_PROVIDED',
  INVALID_FLAT_TYPE: 'INVALID_FLAT_TYPE',
  NO_NUMBER_OF_FLOORS_PROVIDED: 'NO_NUMBER_OF_FLOORS_PROVIDED',
  FLOOR_NUMBER_EXCEEDS_TOTAL_NUMBER_OF_FLOORS:
    'FLOOR_NUMBER_EXCEEDS_TOTAL_NUMBER_OF_FLOORS',
  NO_USABLE_AREA_PROVIDED: 'NO_USABLE_AREA_PROVIDED',
  NO_USABLE_AREA_VALUE_PROVIDED: 'NO_USABLE_AREA_VALUE_PROVIDED',
  NO_USABLE_AREA_TYPE_PROVIDED: 'NO_USABLE_AREA_TYPE_PROVIDED',
  INVALID_USABLE_AREA_TYPE: 'INVALID_USABLE_AREA_TYPE',
};
