export const TOKEN =
  'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ3ZWJzZXJ2aWNlLmUtcG90ZWsiLCJleHAiOjE1OTMyOTUyMDAsImp0aSI6IjM3In0.pEQ2g-S1gEJ3rCCQV8YmR6cj2BYcqDxpmjDMYet5jgSGWmNp6KbomeyfrIPdrLRDJCu96fNsUyE5XmFgpr-eMg';

export const URL =
  'https://www.wuestdimensions.com/ws/calculator/valuation?expand=keyFigureExtension,qualityProfile,valueCorrections';

export const PROPERTY_TYPE = {
  HOUSE: 'HOUSE',
  FLAT: 'FLAT',
};
export const HED_METHOD = {
  SFH: 'HED_SFH',
  CON: 'HED_CON',
};

export const RESIDENCE_TYPE = {
  MAIN: 'MAIN_RESIDENCE',
  SECOND: 'SECOND_RESIDENCE',
};

export const MINERGIE_CERTIFICATE = {
  WITHOUT: 'WITHOUT_CERTIFICATE',
  P: 'MINERGIE_P',
  ECO: 'MINERGIE_ECO',
  P_ECO: 'MINERGIE_P_ECO',
  OTHER: 'OTHER_CERTIFICATE',
};

export const HOUSE_TYPE = {
  DETACHED: 'DETACHED',
  ATTACHED_END: 'ATTACHED_END_BUILDING',
  ATTACHED_MID: 'ATTACHED_MID_TERRACE_BUILDING',
};

export const FLAT_TYPE = {
  SINGLE_FLOOR: 'SINGLE_FLOOR_APARTMENT',
  DUPLEX: 'DUPLEX_APARTMENT',
  PENTHOUSE: 'PENTHOUSE_APARTMENT',
  PENTHOUSE_DUPLEX: 'PENTHOUSE_MAISONETTE',
  GROUND_FLOOR: 'TERRACE_APARTMENT',
};

// TODO: check size of array
export const FLOOR_NUMBER = [
  'GROUND_FLOOR',
  'FIRST_FLOOR',
  'SECOND_FLOOR',
  'THIRD_FLOOR',
  'FOURTH_FLOOR',
  'FIFTH_FLOOR',
  'SIXTH_FLOOR',
  'SEVENTH_FLOOR',
  'EIGHTH_FLOOR',
  'NINTH_FLOOR',
  'TENTH_FLOOR',
  'ELEVENTH_FLOOR',
  'TWELVTH_FLOOR',
  'THIRTEENTH_FLOOR',
  'FOURTEETNH_FLOOR',
  'FIFTEENTH_FLOOR',
  'SIXTEENTH_FLOOR',
  'SEVENTEENTH_FLOOR',
  'EIGHTEENTH_FLOOR',
  'NINETEENTH_FLOOR',
  'TWENTIETH_FLOOR',
];

export const VOLUME_TYPE = {
  SIA_416: 'SIA_416',
  SIA_116: 'SIA_116',
  BIC: 'BIC',
};

export const AREA_TYPE = {
  NET: 'NIA',
  GROSS: 'NLS',
};

export const QUALITY = {
  CONDITION: {
    NEEDS_RENNOVATION: 1,
    INTACT: 3,
    EXCELLENT: 5,
  },
  STANDARD: {
    UNSATISFACTORY: 1,
    AVERAGE: 3,
    HIGH: 4.5,
  },
  SITUATION: {
    BAD: 1.5,
    AVERAGE: 2,
    GOOD: 4,
  },
};

export const JSON_DATA_STRUCTURE = {
  embedded: [
    { rel: 'valueCorrections' },
    { rel: 'objectData', value: { embedded: [{ rel: 'buildings' }] } },
    { rel: 'qualityProfile' },
  ],
};

export const WUEST_ERRORS = {
  NO_PROPERTY_DATA_PROVIDED: 'NO_PROPERTY_DATA_PROVIDED',
  NO_PROPERTY_FOUND: 'NO_PROPERTY_FOUND',
  NO_FLOOR_NUMBER_PROVIDED: 'NO_FLOOR_NUMBER_PROVIDED',
  INVALID_FLOOR_NUMBER: 'INVALID_FLOOR_NUMBER',
  NO_ADDRESS_PROVIDED: 'NO_ADDRESS_PROVIDED',
  NO_RESIDENCE_TYPE_PROVIDED: 'NO_RESIDENCE_TYPE_PROVIDED',
  INVALID_RESIDENCE_TYPE: 'INVALID_RESIDENCE_TYPE',
  NO_ADDRESS_LINE_1_PROVIDED: 'NO_ADDRESS_LINE_1_PROVIDED',
  NO_ZIPCODE_PROVIDED: 'NO_ZIPCODE_PROVIDED',
  NO_CITY_PROVIDED: 'NO_CITY_PROVIDED',
  NO_COUNTRY_PROVIDED: 'NO_COUNTRY_PROVIDED',
  NO_HOUSE_TYPE_PROVIDED: 'NO_HOUSE_TYPE_PROVIDED',
  INVALID_HOUSE_TYPE: 'INVALID_HOUSE_TYPE',
  NO_BUILDING_VOLUME_PROVIDED: 'NO_BUILDING_VOLUME_PROVIDED',
  NO_BUILDING_VOLUME_VALUE_PROVIDED: 'NO_BUILDING_VOLUME_VALUE_PROVIDED',
  NO_BUILDING_VOLUME_TYPE_PROVIDED: 'NO_BUILDING_VOLUME_TYPE_PROVIDED',
  INVALID_BUILDING_VOLUME_TYPE: 'INVALID_BUILDING_VOLUME_TYPE',
  NO_LANDPLOT_AREA_PROVIDED: 'NO_LANDPLOT_AREA_PROVIDED',
  NO_PARKING_PROVIDED: 'NO_PARKING_PROVIDED',
  NO_INSIDE_PARKING_PROVIDED: 'NO_INSIDE_PARKING_PROVIDED',
  NO_OUTSIDE_PARKING_PROVIDED: 'NO_OUTSIDE_PARKING_PROVIDED',
  NO_NUMBER_OF_ROOMS_PROVIDED: 'NO_NUMBER_OF_ROOMS_PROVIDED',
  NO_CONSTRUCTION_YEAR_PROVIDED: 'NO_CONSTRUCTION_YEAR_PROVIDED',
  NO_MINERGIE_CERTIFICATE_PROVIDED: 'NO_MINERGIE_CERTIFICATE_PROVIDED',
  INVALID_MINERGIE_CERTIFICATE: 'INVALID_MINERGIE_CERTIFICATE',
  NO_QUALITY_PROFILE_PROVIDED: 'NO_QUALITY_PROFILE_PROVIDED',
  NO_QUALITY_PROFILE_STANDARD_PROVIDED: 'NO_QUALITY_PROFILE_STANDARD_PROVIDED',
  NO_QUALITY_PROFILE_CONDITION_PROVIDED:
    'NO_QUALITY_PROFILE_CONDITION_PROVIDED',
  NO_QUALITY_PROFILE_SITUATION_PROVIDED:
    'NO_QUALITY_PROFILE_SITUATION_PROVIDED',
  INVALID_QUALITY_PROFILE_STANDARD: 'INVALID_QUALITY_PROFILE_STANDARD',
  INVALID_QUALITY_PROFILE_CONDITION: 'INVALID_QUALITY_PROFILE_CONDITION',
  INVALID_QUALITY_PROFILE_SITUATION: 'INVALID_QUALITY_PROFILE_SITUATION',
  NO_FLAT_TYPE_PROVIDED: 'NO_FLAT_TYPE_PROVIDED',
  INVALID_FLAT_TYPE: 'INVALID_FLAT_TYPE',
  NO_NUMBER_OF_FLOORS_PROVIDED: 'NO_NUMBER_OF_FLOORS_PROVIDED',
  FLOOR_NUMBER_EXCEEDS_TOTAL_NUMBER_OF_FLOORS:
    'FLOOR_NUMBER_EXCEEDS_TOTAL_NUMBER_OF_FLOORS',
  NO_USABLE_AREA_PROVIDED: 'NO_USABLE_AREA_PROVIDED',
  NO_USABLE_AREA_VALUE_PROVIDED: 'NO_USABLE_AREA_VALUE_PROVIDED',
  NO_USABLE_AREA_TYPE_PROVIDED: 'NO_USABLE_AREA_TYPE_PROVIDED',
  INVALID_USABLE_AREA_TYPE: 'INVALID_USABLE_AREA_TYPE',
};
