export const TASKS_COLLECTION = 'tasks';

export const TASK_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const TASK_TYPE = {
  VERIFY: 'VERIFY',
  AUCTION: 'AUCTION',
  LENDER_CHOSEN: 'LENDER_CHOSEN',
  CUSTOM: 'CUSTOM',
  ADD_ASSIGNED_TO: 'ADD_ASSIGNED_TO',
  USER_ADDED_FILE: 'USER_ADDED_FILE',
};

export const TASK_QUERIES = {
  TASKS: 'TASKS',
  UNASSIGNED_TASKS: 'UNASSIGNED_TASKS',
  TASKS_FOR_DOC: 'TASKS_FOR_DOC',
  SIDENAV_TASKS: 'SIDENAV_TASKS',
};
