export const TASK_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const TASK_TYPE = {
  VERIFY: 'VERIFY',
  AUCTION: 'AUCTION',
  LENDER_CHOSEN: 'LENDER_CHOSEN',
  CUSTOM: 'CUSTOM',
};

export const TASK_QUERIES = {
  TASKS: 'TASKS',
};
