const getCantons = () => [
  { key: 'AG', name: 'Aargau' },
  { key: 'AR', name: 'Appenzell Ausserrhoden' },
  { key: 'AI', name: 'Appenzell Innerrhoden' },
  { key: 'BL', name: 'Basel-Land' },
  { key: 'BS', name: 'Basel-Stadt' },
  { key: 'BE', name: 'Bern' },
  { key: 'FR', name: 'Fribourg' },
  { key: 'GE', name: 'Genève' },
  { key: 'GL', name: 'Glarus' },
  { key: 'GR', name: 'Graubünden' },
  { key: 'JU', name: 'Jura' },
  { key: 'LU', name: 'Luzern' },
  { key: 'NE', name: 'Neuchâtel' },
  { key: 'NW', name: 'Nidwalden' },
  { key: 'OW', name: 'Obwalden' },
  { key: 'SG', name: 'St. Gallen' },
  { key: 'SH', name: 'Schaffhausen' },
  { key: 'SZ', name: 'Schwyz' },
  { key: 'SO', name: 'Solothurn' },
  { key: 'TG', name: 'Thurgau' },
  { key: 'TI', name: 'Ticino' },
  { key: 'UR', name: 'Uri' },
  { key: 'VD', name: 'Vaud' },
  { key: 'VS', name: 'Valais' },
  { key: 'ZG', name: 'Zug' },
  { key: 'ZH', name: 'Zürich' },
];

export default getCantons;
