export const ADMIN_ACTION_TYPE = {
  VERIFY: 'VERIFY',
  AUCTION: 'AUCTION',
  LENDER_CHOSEN: 'LENDER_CHOSEN',
};

export const ADMIN_ACTION_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  PARENT_DELETED: 'PARENT_DELETED',
  CANCELLED: 'CANCELLED',
};
