export const INSURANCES_COLLECTION = 'insurances';

export const INSURANCE_STATUS = {
  SUGGESTED: 'SUGGESTED',
  SIGNED: 'SIGNED',
  DECLINED: 'DECLINED',
  POLICED: 'POLICED',
};

export const INSURANCE_PREMIUM_FREQUENCY = {
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY',
  BIANNUAL: 'BIANNUAL',
  YEARLY: 'YEARLY',
  SINGLE: 'SINGLE',
};

export const INSURANCE_QUERIES = {
  INSURANCE_SEARCH: 'INSURANCE_SEARCH',
};
