// @flow
export const PROPERTIES_COLLECTION = 'properties';

export const PROPERTY_STATUS = {
  SOLD: 'SOLD',
  FOR_SALE: 'FOR_SALE',
};

export const RESIDENCE_TYPE = {
  MAIN_RESIDENCE: 'MAIN_RESIDENCE',
  SECOND_RESIDENCE: 'SECOND_RESIDENCE',
  INVESTMENT: 'INVESTMENT',
};

export const PROPERTY_TYPE = {
  FLAT: 'FLAT',
  HOUSE: 'HOUSE',
};

export const VOLUME_NORM = {
  SIA_416: 'SIA_416',
  SIA_116: 'SIA_116',
  BIC: 'BIC',
};

export const AREA_NORM = {
  NIA: 'NIA',
  NLS: 'NLS',
};

export const PROPERTY_QUERIES = {
  PROPERTY_ASSIGNED_TO: 'PROPERTY_ASSIGNED_TO',
  SIDENAV_PROPERTIES: 'SIDENAV_PROPERTIES',
  PROPERTY_SEARCH: 'PROPERTY_SEARCH',
  USER_PROPERTY: 'USER_PROPERTY',
  ADMIN_PROPERTY: 'ADMIN_PROPERTY',
  ADMIN_PROPERTIES: 'ADMIN_PROPERTIES',
};

export const VALUATION_STATUS = {
  NONE: 'NONE',
  DONE: 'DONE',
  ERROR: 'ERROR',
};

export const HOUSE_TYPE = {
  DETACHED: 'DETACHED',
  ATTACHED_END_BUILDING: 'ATTACHED_END_BUILDING',
  ATTACHED_MID_TERRACE_BUILDING: 'ATTACHED_MID_TERRACE_BUILDING',
};

export const FLAT_TYPE = {
  SINGLE_FLOOR_APARTMENT: 'SINGLE_FLOOR_APARTMENT',
  DUPLEX_APARTMENT: 'DUPLEX_APARTMENT',
  PENTHOUSE_APARTMENT: 'PENTHOUSE_APARTMENT',
  PENTHOUSE_MAISONETTE: 'PENTHOUSE_MAISONETTE',
  TERRACE_APARTMENT: 'TERRACE_APARTMENT',
};

export const MINERGIE_CERTIFICATE = {
  WITHOUT_CERTIFICATE: 'WITHOUT_CERTIFICATE',
  MINERGIE_P: 'MINERGIE_P',
  MINERGIE_ECO: 'MINERGIE_ECO',
  MINERGIE_P_ECO: 'MINERGIE_P_ECO',
  OTHER_CERTIFICATE: 'OTHER_CERTIFICATE',
};

export const QUALITY = {
  CONDITION: {
    NEEDS_RENOVATION: 'NEEDS_RENOVATION',
    INTACT: 'INTACT',
    EXCELLENT: 'EXCELLENT',
  },
  STANDARD: {
    UNSATISFACTORY: 'UNSATISFACTORY',
    AVERAGE: 'AVERAGE',
    HIGH: 'HIGH',
  },
};
