export const ERROR_CODES = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
};

export const LOT_ERRORS = {
  PROMOTION_LOT_RESERVED_OR_SOLD: 'PROMOTION_LOT_RESERVED_OR_SOLD',
};
