export const LENDERS_COLLECTION = 'lenders';

export const LENDERS_QUERIES = {
  LOAN_LENDERS: 'LOAN_LENDERS',
};

export const LENDERS_STATUS = {
  TO_CONTACT: 'TO_CONTACT',
  CONTACTED: 'CONTACTED',
  OFFER_RECEIVED: 'OFFER_RECEIVED',
  TO_EXCLUDE: 'TO_EXCLUDE',
};
