export const LENDERS_COLLECTION = 'lenders';

export const LENDER_STATUS = {
  TO_BE_CONTACTED: 'TO_BE_CONTACTED',
  CONTACTED: 'CONTACTED',
  OFFER_RECEIVED: 'OFFER_RECEIVED',
  TO_EXCLUDE: 'TO_EXCLUDE',
};
