export const INSURANCE_REQUESTS_COLLECTION = 'insuranceRequests';

export const INSURANCE_REQUEST_STATUS = {
  LEAD: 'LEAD',
  QUALIFIED_LEAD: 'QUALIFIED_LEAD',
  ONGOING: 'ONGOING',
  CLOSING: 'CLOSING',
  BILLING: 'BILLING',
  FINALIZED: 'FINALIZED',
  PENDING: 'PENDING',
  UNSUCCESSFUL: 'UNSUCCESSFUL',
  TEST: 'TEST',
};

export const INSURANCE_REQUEST_STATUS_ORDER = [
  INSURANCE_REQUEST_STATUS.LEAD,
  INSURANCE_REQUEST_STATUS.QUALIFIED_LEAD,
  INSURANCE_REQUEST_STATUS.PENDING,
  INSURANCE_REQUEST_STATUS.ONGOING,
  INSURANCE_REQUEST_STATUS.CLOSING,
  INSURANCE_REQUEST_STATUS.BILLING,
  INSURANCE_REQUEST_STATUS.FINALIZED,
  INSURANCE_REQUEST_STATUS.UNSUCCESSFUL,
  INSURANCE_REQUEST_STATUS.TEST,
];

export const INSURANCE_REQUEST_QUERIES = {
  INSURANCE_REQUEST_SEARCH: 'INSURANCE_REQUEST_SEARCH',
};
