export const ORG_NAME = 'Organisation 1';
export const PRO_EMAIL = 'dev+pro1@e-potek.ch';
export const PRO_EMAIL_2 = 'dev+pro2@e-potek.ch';
export const PRO_EMAIL_3 = 'dev+pro3@e-potek.ch';
export const PRO_PASSWORD = '12345';
export const USER_EMAIL = 'dev@e-potek.ch';
export const USER_PASSWORD = '12345';
export const DEV_EMAIL = 'florian@e-potek.ch';
export const ADMIN_EMAIL = 'lydia@e-potek.ch';
