export const OFFER_TYPE = {
  STANDARD: 'STANDARD',
  COUNTERPARTS: 'COUNTERPARTS',
};

export const OFFERS_COLLECTION = 'offers';

export const OFFER_QUERIES = {
  LOAN_OFFERS: 'LOAN_OFFERS',
  ADMIN_OFFERS: 'ADMIN_OFFERS',
};
