// import loanBaseFragment from '../../../loans/queries/loanFragments/loanBaseFragment';
import { simpleUserFragment } from './userFragments';
// import loanFragment from '../../../loans/queries/loanFragments/loanFragment';

export default {
  ...simpleUserFragment,
  assignedEmployee: simpleUserFragment,
  emails: 1,
  createdAt: 1,
  updatedAt: 1,
  loans: {
    additionalDocuments: { id: 1, label: 1, requiredByAdmin: 1 },
    borrowerIds: 1,
    borrowers: { firstName: 1, lastName: 1, name: 1 },
    canton: 1,
    createdAt: 1,
    currentOwner: 1,
    enableOffers: 1,
    futureOwner: 1,
    hasPromotion: 1,
    logic: 1,
    name: 1,
    otherOwner: 1,
    previousLender: 1,
    previousLoanTranches: 1,
    promotions: {
      name: 1,
      address: 1,
      contacts: 1,
    },
    promotionOptions: {
      promotionLots: {
        name: 1,
        status: 1,
        reducedStatus: 1,
        value: 1,
        // FIXME: This should be a userPropertyFragment, but there are circular dependency issues!!!!
        properties: { value: 1 },
      },
      name: 1,
      custom: 1,
      attributedToMe: 1,
      priority: 1,
      promotion: 1,
      value: 1,
      solvency: 1,
    },
    properties: { value: 1, address1: 1 },
    propertyIds: 1,
    purchaseType: 1,
    residenceType: 1,
    selectedStructure: 1,
    status: 1,
    structure: 1,
    structures: 1,
    updatedAt: 1,
    userId: 1,
    verificationStatus: 1,
  },
  apiToken: 1,
};
