export const EVENTS = {
  USER_CREATED: 'USER_CREATED',
  USER_FOLLOWED_IMPERSONATING_ADMIN: 'USER_FOLLOWED_IMPERSONATING_ADMIN',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_VERIFIED_EMAIL: 'USER_VERIFIED_EMAIL',

  PROMOTION_CREATED: 'PROMOTION_CREATED',
  PROMOTION_CUSTOMER_INVITED: 'PROMOTION_CUSTOMER_INVITED',
  PROMOTION_LOT_STATUS_UPDATED: 'PROMOTION_LOT_STATUS_UPDATED',

  PROPERTY_CUSTOMER_INVITED: 'PROPERTY_CUSTOMER_INVITED',

  LOAN_ANONYMOUS_LOAN_CLAIMED: 'LOAN_ANONYMOUS_LOAN_CLAIMED',
  LOAN_BORROWERS_INSERTED: 'LOAN_BORROWERS_INSERTED',
  LOAN_STATUS_CHANGED: 'LOAN_STATUS_CHANGED',
  LOAN_COMPLETED_A_STRUCTURE: 'LOAN_COMPLETED_A_STRUCTURE',
  LOAN_CREATED: 'LOAN_CREATED',
  LOAN_MADE_PROGRESS: 'LOAN_MADE_PROGRESS',
  LOAN_MAX_PROPERTY_VALUE_CALCULATED: 'LOAN_MAX_PROPERTY_VALUE_CALCULATED',
  LOAN_SET_STATUS: 'LOAN_SET_STATUS',
  LOAN_SET_STEP: 'LOAN_SET_STEP',
  LOAN_TASK_ADDED: 'LOAN_TASK_ADDED',
  LOAN_TASK_UPDATED: 'LOAN_TASK_UPDATED',

  CTA_CLICKED: 'CTA_CLICKED',

  API_CALLED: 'API_CALLED',

  PRO_INVITED_CUSTOMER: 'PRO_INVITED_CUSTOMER',
  PRO_INVITED_PRO: 'PRO_INVITED_PRO',

  ADMIN_INVITED_USER: 'ADMIN_INVITED_USER',

  INTERCOM_STARTED_A_CONVERSATION: 'INTERCOM_STARTED_A_CONVERSATION',
  INTERCOM_RECEIVED_ADMIN_RESPONSE: 'INTERCOM_RECEIVED_ADMIN_RESPONSE',
  INTERCOM_SENT_A_MESSAGE: 'INTERCOM_SENT_A_MESSAGE',
  INTERCOM_OPENED_MESSENGER: 'INTERCOM_OPENED_MESSENGER',

  DRIP_SUBSCRIBER_CREATED: 'DRIP_SUBSCRIBER_CREATED',
  DRIP_SUBSCRIBER_UPDATED: 'DRIP_SUBSCRIBER_UPDATED',
  DRIP_SUBSCRIBER_REMOVED: 'DRIP_SUBSCRIBER_REMOVED',
  DRIP_SUBSCRIBER_EVENT_RECORDED: 'DRIP_SUBSCRIBER_EVENT_RECORDED',
  DRIP_SUBSCRIBER_LOST: 'DRIP_SUBSCRIBER_LOST',
  DRIP_SUBSCRIBER_QUALIFIED: 'DRIP_SUBSCRIBER_QUALIFIED',
  DRIP_SUBSCRIBER_BOOKED_AN_EVENT: 'DRIP_USER_BOOKED_AN_EVENT',
  DRIP_SUBSCRIBER_UNSUBSCRIBED: 'DRIP_SUBSCRIBER_UNSUBSCRIBED',
  DRIP_SUBSCRIBER_RECEIVED_EMAIL: 'DRIP_SUBSCRIBER_RECEIVED_EMAIL',
  DRIP_SUBSCRIBER_OPENED_EMAIL: 'DRIP_SUBSCRIBER_OPENED_EMAIL',
  DRIP_SUBSCRIBER_CLICKED_EMAIL: 'DRIP_SUBSCRIBER_CLICKED_EMAIL',
  DRIP_SUBSCRIBER_BOUNCED: 'DRIP_SUBSCRIBER_BOUNCED',
  DRIP_SUBSCRIBER_COMPLAINED: 'DRIP_SUBSCRIBER_COMPLAINED',
};

export default EVENTS;
