export const EVENTS = {
  USER_CREATED: 'USER_CREATED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_VERIFIED_EMAIL: 'USER_VERIFIED_EMAIL',

  PROMOTION_CREATED: 'PROMOTION_CREATED',
  PROMOTION_CUSTOMER_INVITED: 'PROMOTION_CUSTOMER_INVITED',
  PROMOTION_LOT_STATUS_UPDATED: 'PROMOTION_LOT_STATUS_UPDATED',

  PROPERTY_CUSTOMER_INVITED: 'PROPERTY_CUSTOMER_INVITED',

  LOAN_ANONYMOUS_LOAN_CLAIMED: 'LOAN_ANONYMOUS_LOAN_CLAIMED',
  LOAN_BORROWERS_INSERTED: 'LOAN_BORROWERS_INSERTED',
  LOAN_STATUS_CHANGED: 'LOAN_STATUS_CHANGED',
  LOAN_COMPLETED_A_STRUCTURE: 'LOAN_COMPLETED_A_STRUCTURE',
  LOAN_CREATED: 'LOAN_CREATED',
  LOAN_MADE_PROGRESS: 'LOAN_MADE_PROGRESS',
  LOAN_MAX_PROPERTY_VALUE_CALCULATED: 'LOAN_MAX_PROPERTY_VALUE_CALCULATED',
  LOAN_SET_STATUS: 'LOAN_SET_STATUS',
  LOAN_SET_STEP: 'LOAN_SET_STEP',
  LOAN_TASK_ADDED: 'LOAN_TASK_ADDED',
  LOAN_TASK_UPDATED: 'LOAN_TASK_UPDATED',

  CTA_CLICKED: 'CTA_CLICKED',

  API_CALLED: 'API_CALLED',
};

export default EVENTS;
