export const PROMOTION_LOTS_COLLECTION = 'promotionLots';

export const PROMOTION_LOT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  BOOKED: 'BOOKED',
  SOLD: 'SOLD',
};

export const PROMOTION_LOT_QUERIES = {
  PRO_PROMOTION_LOT: 'PRO_PROMOTION_LOT',
  PROMOTION_LOT_FILES: 'PROMOTION_LOT_FILES',
};
