export const PROMOTION_LOTS_COLLECTION = 'promotionLots';

export const PROMOTION_LOT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  SOLD: 'SOLD',
};

export const PROMOTION_LOT_REDUCED_STATUS = {
  RESERVED_FOR_ME: 'RESERVED_FOR_ME',
  NOT_AVAILABLE: 'NOT_AVAILABLE',
  SOLD_TO_ME: 'SOLD_TO_ME',
};

export const PROMOTION_LOT_QUERIES = {
  APP_PROMOTION_LOT: 'APP_PROMOTION_LOT',
  PRO_PROMOTION_LOT: 'PRO_PROMOTION_LOT',
  PROMOTION_LOT_FILES: 'PROMOTION_LOT_FILES',
};
