// flow-typed signature: adbd8ed9e960c368d0b9a75f52699ef6
// flow-typed version: <<STUB>>/@storybook/react-komposer_v^2.0.4/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react-komposer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react-komposer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react-komposer/dist/compose' {
  declare module.exports: any;
}

declare module '@storybook/react-komposer/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/react-komposer/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react-komposer/dist/compose.js' {
  declare module.exports: $Exports<'@storybook/react-komposer/dist/compose'>;
}
declare module '@storybook/react-komposer/dist/index.js' {
  declare module.exports: $Exports<'@storybook/react-komposer/dist/index'>;
}
declare module '@storybook/react-komposer/dist/utils.js' {
  declare module.exports: $Exports<'@storybook/react-komposer/dist/utils'>;
}
