// @flow
export const REHYDRATE_LOAN = 'REHYDRATE_LOAN';
export const REHYDRATE_PROPERTIES = 'REHYDRATE_PROPERTIES';
export const REHYDRATE_BORROWERS = 'REHYDRATE_BORROWERS';
export const REHYDRATE_DATA = 'REHYDRATE_DATA';
export const UPDATE_STRUCTURE = 'UPDATE_STRUCTURE';
