// Separate these fragments into separate files to avoid cyclic dependencies

export const loanFragment = {
  additionalDocuments: { id: 1, label: 1, requiredByAdmin: 1 },
  borrowerIds: 1,
  borrowers: { firstName: 1, lastName: 1, name: 1 },
  canton: 1,
  createdAt: 1,
  currentOwner: 1,
  enableOffers: 1,
  futureOwner: 1,
  hasPromotion: 1,
  logic: 1,
  name: 1,
  otherOwner: 1,
  previousLender: 1,
  previousLoanTranches: 1,
  promotions: {
    name: 1,
    address: 1,
    contacts: 1,
  },
  properties: { value: 1, address1: 1 },
  propertyIds: 1,
  purchaseType: 1,
  residenceType: 1,
  selectedStructure: 1,
  status: 1,
  structure: 1,
  structures: 1,
  updatedAt: 1,
  userId: 1,
  verificationStatus: 1,
  // $options: { sort: { createdAt: 1 } },
};
